import http from 'node:http';
import { spawn, ChildProcess } from 'node:child_process';
import { beforeAll, afterAll, describe, expect, it } from 'vitest';

const port = 8799; const base = `http://127.0.0.1:${port}`; let serverProcess: ChildProcess;
function request(path: string, method = 'GET', body?: unknown, token?: string): Promise<any> { return new Promise((resolve, reject) => { const payload = body === undefined ? null : JSON.stringify(body); const req = http.request(new URL(path, base), { method, headers: { ...(payload ? { 'content-type': 'application/json', 'content-length': Buffer.byteLength(payload) } : {}), ...(token ? { authorization: `Bearer ${token}` } : {}) } }, res => { let text = ''; res.on('data', chunk => text += chunk); res.on('end', () => { let value: any = text; try { value = JSON.parse(text); } catch {} resolve({ status: res.statusCode, value, headers: res.headers }); }); }); req.on('error', reject); if (payload) req.write(payload); req.end(); }); }
async function waitForHealth() { for (let attempt = 0; attempt < 30; attempt += 1) { try { const result = await request('/health'); if (result.status === 200) return; } catch {} await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('E2E server did not start'); }
describe('campaign API E2E', () => {
  beforeAll(async () => { serverProcess = spawn(process.execPath, ['server/index.js'], { cwd: process.cwd(), env: { ...process.env, PORT: String(port), NODE_ENV: 'test', ENABLE_BACKUPS: '0' }, stdio: 'ignore' }); await waitForHealth(); });
  afterAll(() => { if (serverProcess) serverProcess.kill(); });
  it('recovers realtime events through the stream and history endpoint', async () => { const created = await request('/api/campaigns', 'POST', { name: 'Realtime E2E' }); const stream = await new Promise(resolve => { const req = http.request(new URL(`/api/campaigns/${created.value.campaign.id}/stream`, base), { headers: { authorization: `Bearer ${created.value.gmToken}` } }, res => { let data = ''; res.on('data', chunk => { data += chunk; if (data.includes('connected')) { req.destroy(); resolve(true); } }); }); req.on('error', error => error.code === 'ECONNRESET' ? resolve(true) : resolve(false)); req.end(); }); expect(stream).toBe(true); await request(`/api/campaigns/${created.value.campaign.id}/announcements`, 'POST', { text: 'stream event' }, created.value.gmToken); const events = await request(`/api/campaigns/${created.value.campaign.id}/events?limit=10`, 'GET', undefined, created.value.gmToken); expect(events.status).toBe(200); expect(events.value.events.some((event: any) => event.operation === 'announcement.create')).toBe(true); });
  it('rejects stale simultaneous character edits with a conflict', async () => { const campaign = await request('/api/campaigns', 'POST', { name: 'Conflict E2E' }); const character = await request(`/api/campaigns/${campaign.value.campaign.id}/characters`, 'POST', { name: 'Conflict Hero', className: 'Bard', ancestry: 'Human' }, campaign.value.gmToken); const first = await request(`/api/campaigns/${campaign.value.campaign.id}/characters/${character.value.id}`, 'PATCH', { version: 1, stress: 1 }, campaign.value.gmToken); const second = await request(`/api/campaigns/${campaign.value.campaign.id}/characters/${character.value.id}`, 'PATCH', { version: 1, stress: 2 }, campaign.value.gmToken); expect(first.status).toBe(200); expect(second.status).toBe(409); });
  it('preserves participant identity mapping during import and issues new access', async () => { const campaign = await request('/api/campaigns', 'POST', { name: 'Import E2E' }); const joined = await request(`/api/campaigns/${campaign.value.campaign.id}/join`, 'POST', { nickname: 'Imported Player' }, campaign.value.playerToken); const exported = await request(`/api/campaigns/${campaign.value.campaign.id}/export`, 'GET', undefined, campaign.value.gmToken); const imported = await request('/api/campaigns/import', 'POST', exported.value); expect(imported.status).toBe(201); expect(imported.value.importedParticipants).toHaveLength(1); expect(imported.value.importedParticipants[0].nickname).toBe('Imported Player'); expect(imported.value.importedParticipants[0].participantToken).not.toBe(joined.value.participantToken); });
  it('remaps an assigned character to the imported participant identity', async () => { const campaign = await request('/api/campaigns', 'POST', { name: 'Assignment Import E2E' }); const joined = await request(`/api/campaigns/${campaign.value.campaign.id}/join`, 'POST', { nickname: 'Assigned Player' }, campaign.value.playerToken); const character = await request(`/api/campaigns/${campaign.value.campaign.id}/characters`, 'POST', { name: 'Assigned Hero', className: 'Bard', ancestry: 'Human' }, campaign.value.gmToken); const claimed = await request(`/api/campaigns/${campaign.value.campaign.id}/characters/${character.value.id}/claim`, 'POST', {}, joined.value.participantToken); expect(claimed.status).toBe(200); const exported = await request(`/api/campaigns/${campaign.value.campaign.id}/export`, 'GET', undefined, campaign.value.gmToken); const imported = await request('/api/campaigns/import', 'POST', exported.value); expect(imported.value.importedParticipants[0].characterId).toBeTruthy(); });
  it('creates and retrieves a recovery backup', async () => { const campaign = await request('/api/campaigns', 'POST', { name: 'Backup E2E' }); const backup = await request(`/api/campaigns/${campaign.value.campaign.id}/backup`, 'POST', {}, campaign.value.gmToken); expect(backup.status).toBe(201); const list = await request(`/api/campaigns/${campaign.value.campaign.id}/backups`, 'GET', undefined, campaign.value.gmToken); expect(list.value.backups.length).toBeGreaterThan(0); const downloaded = await request(`/api/campaigns/${campaign.value.campaign.id}/backups/${backup.value.name}`, 'GET', undefined, campaign.value.gmToken); expect(downloaded.value.schemaVersion).toBe(1); });
  it('keeps GM resources private from the public player token', async () => { const campaign = await request('/api/campaigns', 'POST', { name: 'Permissions E2E' }); const publicView = await request(`/api/campaigns/${campaign.value.campaign.id}`, 'GET', undefined, campaign.value.playerToken); expect(publicView.status).toBe(404); const joined = await request(`/api/campaigns/${campaign.value.campaign.id}/join`, 'POST', { nickname: 'Player' }, campaign.value.playerToken); const playerView = await request(`/api/campaigns/${campaign.value.campaign.id}`, 'GET', undefined, joined.value.participantToken); expect(playerView.status).toBe(200); expect(playerView.value.gmLibrary).toBeUndefined(); const participants = await request(`/api/campaigns/${campaign.value.campaign.id}/participants`, 'GET', undefined, joined.value.participantToken); expect(participants.status).toBe(404); });
});
