const classes = require('../src/content/daggerforge/srd/classes.json');
const ancestries = require('../src/content/daggerforge/srd/ancestries.json');
const communities = require('../src/content/daggerforge/srd/communities.json');
const domains = require('../src/content/daggerforge/srd/domains.json');
const equipment = require('../src/content/daggerforge/srd/equipment.json');
const beastforms = require('../src/content/daggerforge/srd/beastforms.json');

const traits = ['agility', 'strength', 'finesse', 'instinct', 'presence', 'knowledge']; const traitPool = ['+2', '+1', '+1', '0', '0', '-1']; const validTraitDistribution = values => traits.every(name => /^[-+]?\d+$/.test(String(values?.[name]?.value ?? values?.[name] ?? ''))) && traitPool.every(value => Object.values(values || {}).filter(item => String(item?.value ?? item) === value).length === traitPool.filter(item => item === value).length);
const emptyTraits = () => Object.fromEntries(traits.map(name => [name, { value: '', marked: false }]));
const cardFor = (name, list) => list.find(item => item.name === name);
const classNames = new Set(classes.map(item => item.name));
const ancestryNames = new Set(ancestries.map(item => item.name));
const communityNames = new Set(communities.map(item => item.name));
const domainNames = new Set(domains.map(item => item.name));
const equipmentNames = new Set([...(equipment.weapons || []), ...(equipment.armor || [])].map(item => item.name));
const subclassFor = (className, subclassName) => {
  const selectedClass = cardFor(className, classes);
  return selectedClass?.subclasses?.[subclassName] || null;
};
const classDomains = className => String(cardFor(className, classes)?.stats?.domains || '').split('&').map(value => value.trim()).filter(Boolean); const unlockedSubclassFeatures = (subclass, level) => [...(subclass?.foundation || []), ...(Number(level) >= 5 ? subclass?.specialization || [] : []), ...(Number(level) >= 8 ? subclass?.mastery || [] : [])]; const thresholdBonusFor = (subclass, level) => unlockedSubclassFeatures(subclass, level).reduce((total, feature) => total + Number(String(feature.description || '').match(/permanent \+(\d+) bonus to all damage thresholds/i)?.[1] || 0), 0);
const validDomainCard = (card, className, level) => { const name = typeof card === 'string' ? card : card?.name; const source = cardFor(name, domains); return Boolean(source && classDomains(className).includes(source.domain) && Number(source.level) <= Number(level || 1)); };
const validBeastform = name => beastforms.find(item => item.name === name);
const specializedFor = (body, className) => {
  const result = {};
  if (className === 'Druid') { result.beastformName = String(body.beastformName || ''); result.beastformStress = Number.isInteger(Number(body.beastformStress)) ? Number(body.beastformStress) : 0; }
  if (className === 'Druid' && body.subclassName === 'Warden of the Elements') result.channelElement = String(body.channelElement || '');
  if (className === 'Ranger' && body.subclassName === 'Beastbound') result.companion = { name: String(body.companion?.name || body.companionName || ''), evasion: 10, stress: Number(body.companion?.stress || 0), stressMax: 6, experiences: Array.isArray(body.companion?.experiences) ? body.companion.experiences.slice(0, 2) : [] };
  if (className === 'Sorcerer' && body.subclassName === 'Elemental Origin') result.element = String(body.element || '');
  if (className === 'Seraph' && body.subclassName === 'Divine Wielder') result.prayerDice = Array.isArray(body.prayerDice) ? body.prayerDice.filter(value => Number.isInteger(Number(value))).map(Number).slice(0, 12) : [];
  if (className === 'Warrior' && body.subclassName === 'Call of the Slayer') result.slayerDice = Array.isArray(body.slayerDice) ? body.slayerDice.filter(value => Number.isInteger(Number(value))).map(Number).slice(0, 12) : [];
  return result;
};
const armorModifiers = armor => {
  const feature = String(armor?.feature || '');
  return { evasion: feature.includes('Very Heavy') ? -2 : feature.includes('Heavy') ? -1 : feature.includes('Flexible') ? 1 : feature.includes('Difficult') ? -1 : 0, allTraits: feature.includes('Difficult') ? -1 : 0, agility: feature.includes('Very Heavy') ? -1 : 0 };
};
const derivedValuesFor = character => { const selectedClass = cardFor(character.className, classes); const ancestry = cardFor(character.ancestry, ancestries); const armor = cardFor(character.armorName, equipment.armor || []); const subclass = subclassFor(character.className, character.subclassName); const evasion = selectedClass?.stats?.evasion == null ? null : selectedClass.stats.evasion + armorModifiers(armor).evasion; const hpMax = selectedClass?.stats?.hp == null ? null : selectedClass.stats.hp + ((ancestry?.features || []).some(feature => /additional Hit Point slot/i.test(String(feature))) ? 1 : 0); return { hpMax, evasion, armorScore: armor?.score ?? 0, majorThreshold: armor ? armor.minor + Number(character.level || 1) + thresholdBonusFor(subclass, character.level) : null, severeThreshold: armor ? armor.major + Number(character.level || 1) + thresholdBonusFor(subclass, character.level) : null }; };

function buildCharacterFromChoices(body, id) {
  const selectedClass = cardFor(body.className, classes);
  const level = Number.isInteger(Number(body.level)) ? Math.min(10, Math.max(1, Number(body.level))) : 1;
  const classTraits = selectedClass?.stats?.suggestedTraits?.split(',').map(x => x.trim()) || [];
  const armor = cardFor(body.armorName || selectedClass?.stats?.suggestedArmor, equipment.armor || []);
  const primary = cardFor(body.primaryWeaponName || body.primaryWeapon || selectedClass?.stats?.suggestedPrimary, equipment.weapons || []);
  const secondary = cardFor(body.secondaryWeaponName || body.secondaryWeapon || selectedClass?.stats?.suggestedSecondary, equipment.weapons || []);
  const experienceNames = Array.isArray(body.experiences) ? body.experiences : [];
  const domainCardNames = Array.isArray(body.domainCardNames) ? body.domainCardNames : [];
  const ancestry = cardFor(body.ancestry, ancestries); const community = cardFor(body.community, communities); const selectedSubclass = subclassFor(body.className, body.subclassName);
  const domainCards = domainCardNames.slice(0, 11).map((name, index) => { const card = cardFor(name, domains); return card ? { ...card, inVault: index >= 5 } : { name: String(name), inVault: index >= 5 }; });
  const armorScore = armor?.score ?? 0; const starterInventory = [armor?.name, primary?.name, secondary?.name].filter(Boolean); const armorAdjustment = armorModifiers(armor); const maxHp = selectedClass?.stats?.hp ?? (Number.isFinite(Number(body.hpMax)) ? Number(body.hpMax) : 6); const derivedHpMax = maxHp + ((ancestry?.features || []).some(feature => /additional Hit Point slot/i.test(String(feature))) ? 1 : 0);
  const submittedTraits = body.traits && typeof body.traits === 'object' ? Object.fromEntries(traits.map(name => [name, { value: String((body.traits[name]?.value ?? body.traits[name] ?? classTraits[traits.indexOf(name)] ?? '')), marked: Boolean(body.traits[name]?.marked) }])) : Object.fromEntries(traits.map((name, index) => [name, { value: classTraits[index] || '', marked: false }]));
  const submittedExperiences = experienceNames.slice(0, 2).map(item => typeof item === 'object' ? { text: String(item.text || '').slice(0, 120), modifier: String(item.modifier || '+2') } : { text: String(item).slice(0, 120), modifier: '+2' });
  const submittedInventory = Array.from(new Set([...starterInventory, ...(Array.isArray(body.inventory) ? body.inventory : [])])).slice(0, 50).map(item => String(item).slice(0, 160)); const normalizeAnswers = value => Array.isArray(value) ? value.slice(0, 3).map(item => typeof item === 'object' ? { question: String(item.question || '').slice(0, 500), answer: String(item.answer || '').slice(0, 2000) } : { question: '', answer: String(item || '').slice(0, 2000) }) : [];
  return { id, name: String(body.name || 'New Character').slice(0, 120), className: selectedClass?.name || String(body.className || ''), subclassName: String(body.subclassName || ''), ancestry: ancestry?.name || String(body.ancestry || ''), community: community?.name || String(body.community || ''), color: String(body.color || '#a88be3'), initials: String(body.initials || body.name || 'PC').split(/\s+/).map(x => x[0]).join('').slice(0, 4), level, hp: Number.isInteger(Number(body.hp)) ? Number(body.hp) : derivedHpMax, hpMax: derivedHpMax, hope: Number.isInteger(Number(body.hope)) ? Number(body.hope) : 2, stress: Number.isInteger(Number(body.stress)) ? Number(body.stress) : 0, armor: armorScore, armorName: armor?.name || '', armorFeature: armor?.feature || '', armorSlots: Array.from({ length: armorScore }, (_, index) => ({ id: index + 1, marked: false })), hopeMax: 6, stressMax: 6, evasion: selectedClass?.stats?.evasion == null ? null : selectedClass.stats.evasion + armorAdjustment.evasion, armorScore, majorThreshold: armor ? armor.minor + level + thresholdBonusFor(selectedSubclass, level) : null, severeThreshold: armor ? armor.major + level + thresholdBonusFor(selectedSubclass, level) : null, traits: submittedTraits, experiences: submittedExperiences, domainCards, ancestryCard: ancestry || null, communityCard: community || null, primaryWeapon: primary ? weaponRecord(primary, 'Primary') : null, secondaryWeapon: secondary ? weaponRecord(secondary, 'Secondary') : null, complete: body.complete === true, ancestryFeatures: ancestry?.features || [], communityFeatures: community?.features || [], classFeatures: [...(selectedClass?.classFeatures || []), ...unlockedSubclassFeatures(selectedSubclass, level)], classBackgroundQuestions: selectedClass?.backgroundQuestions || [], classConnectionQuestions: selectedClass?.connectionQuestions || [], backgroundAnswers: normalizeAnswers(body.backgroundAnswers), connectionAnswers: normalizeAnswers(body.connectionAnswers), ownerId: null, inventory: submittedInventory, privateNotes: String(body.privateNotes || '').slice(0, 5000), ...specializedFor(body, selectedClass?.name || String(body.className || '')), version: 1, lastFieldVersions: {} };
}

function weaponRecord(source, slot) { return { sourceId: source.id, name: source.name, traitRange: `${source.trait} - ${source.range}`, damageDice: `${source.damage} ${source.damageType === 'Magical' ? 'mag' : 'phy'}`, burden: source.burden || '', feature: source.feature || '', slot }; }

function validateCharacterModel(character, changes) {
  const merged = { ...character, ...changes }; const requiredText = [['name', 120], ['className', 80], ['ancestry', 80]];
  for (const [key, max] of requiredText) if (key in changes && (typeof changes[key] !== 'string' || !changes[key].trim() || changes[key].length > max)) return `${key} is required and must be ${max} characters or fewer.`;
  if ('className' in changes && !classNames.has(changes.className)) return 'Choose a class from the Daggerheart content set.';
  if ('ancestry' in changes && !ancestryNames.has(changes.ancestry)) return 'Choose an ancestry from the Daggerheart content set.';
  if ('community' in changes && changes.community && !communityNames.has(changes.community)) return 'Choose a community from the Daggerheart content set.';
  if (merged.subclassName && !subclassFor(merged.className, merged.subclassName)) return 'Choose a subclass that belongs to the selected class.';
  if ('armorName' in changes && changes.armorName && !cardFor(changes.armorName, equipment.armor || [])) return 'Choose armor from the Daggerheart equipment set.';
  const numeric = [['hp', 0, Number(merged.hpMax || 0)], ['hpMax', 1, 24], ['hope', 0, 6], ['stress', 0, 6], ['armor', 0, 12], ['level', 1, 10], ['evasion', 0, 30], ['armorScore', 0, 30], ['majorThreshold', 0, 60], ['severeThreshold', 0, 60], ['beastformStress', 0, 6]];
  for (const [key, min, max] of numeric) if (key in changes && changes[key] !== null && (!Number.isInteger(Number(changes[key])) || Number(changes[key]) < min || Number(changes[key]) > max)) return `${key} must be an integer between ${min} and ${max}.`;
  if (Number(merged.hp) > Number(merged.hpMax)) return 'HP cannot exceed HP maximum.';
  if ('hpMax' in changes && Number(changes.hpMax) < Number(character.hp || 0)) return 'HP maximum cannot be lower than current HP.';
  const derived = derivedValuesFor(merged); for (const key of ['hpMax', 'evasion', 'armorScore', 'majorThreshold', 'severeThreshold']) if (key in changes && derived[key] !== null && Number(changes[key]) !== Number(derived[key])) return `${key} is derived from the selected character options and cannot be overridden.`;
  if ('traits' in changes && (!changes.traits || typeof changes.traits !== 'object' || Array.isArray(changes.traits) || traits.some(name => !changes.traits[name] || typeof changes.traits[name].value !== 'string' || !/^[-+]?\d+$/.test(changes.traits[name].value) || Number(changes.traits[name].value) < -3 || Number(changes.traits[name].value) > 3))) return 'Traits must contain all six modifiers from -3 to +3.';
  if ('experiences' in changes && (!Array.isArray(changes.experiences) || changes.experiences.length > 2 || changes.experiences.some(item => !item || typeof item.text !== 'string' || !item.text.trim() || item.text.length > 120 || typeof item.modifier !== 'string' || !/^[-+]?\d+$/.test(item.modifier)))) return 'Characters may have up to two experiences with text and numeric modifiers.';
  if ('domainCards' in changes && (!Array.isArray(changes.domainCards) || changes.domainCards.length > 50 || changes.domainCards.filter(item => typeof item === 'object' && item && !item.inVault).length > 5 || changes.domainCards.some(item => !item || !domainNames.has(typeof item === 'string' ? item : item.name) || !validDomainCard(item, merged.className, merged.level)))) return 'Choose cards from your class domains at or below your character level.';
  for (const key of ['primaryWeapon', 'secondaryWeapon']) if (key in changes && changes[key] && (!changes[key].name || (changes[key].sourceId && !equipmentNames.has(changes[key].name)))) return `${key} must reference a known equipment entry.`;
  if ('inventory' in changes && (!Array.isArray(changes.inventory) || changes.inventory.length > 50 || changes.inventory.some(item => typeof item !== 'string' || !item.trim() || item.length > 160))) return 'Inventory must contain at most 50 named items.';
  if ('beastformName' in changes && changes.beastformName && !validBeastform(changes.beastformName)) return 'Choose a valid Beastform.';
  if (merged.className === 'Druid' && merged.beastformName && !validBeastform(merged.beastformName)) return 'Choose a valid Beastform.';
  if (merged.className === 'Druid' && merged.subclassName === 'Warden of the Elements' && merged.channelElement && !['air', 'earth', 'fire', 'water'].includes(String(merged.channelElement).toLowerCase())) return 'Choose air, earth, fire, or water as your element.'; if ('prayerDice' in changes && (!Array.isArray(changes.prayerDice) || changes.prayerDice.length > 12 || changes.prayerDice.some(value => !Number.isInteger(Number(value)) || Number(value) < 1 || Number(value) > 4))) return 'Prayer Dice must contain up to twelve d4 values.'; if ('slayerDice' in changes && (!Array.isArray(changes.slayerDice) || changes.slayerDice.length > 12 || changes.slayerDice.some(value => !Number.isInteger(Number(value)) || Number(value) < 1 || Number(value) > 6))) return 'Slayer Dice must contain up to twelve d6 values.';
  if (merged.className === 'Ranger' && merged.subclassName === 'Beastbound' && merged.companion && (!String(merged.companion.name || '').trim() || !Array.isArray(merged.companion.experiences) || merged.companion.experiences.length > 2 || Number(merged.companion.stress) < 0 || Number(merged.companion.stress) > Number(merged.companion.stressMax || 6))) return 'Beastbound characters need a named companion with valid Stress and up to two Experiences.'; if (merged.className === 'Ranger' && merged.subclassName === 'Beastbound' && merged.companion?.experiences?.some(item => !item || typeof item.text !== 'string' || !item.text.trim() || item.text.length > 120 || typeof item.modifier !== 'string' || !/^[-+]?\d+$/.test(item.modifier))) return 'Companion Experiences need text and numeric modifiers.';
  if (merged.className === 'Sorcerer' && merged.subclassName === 'Elemental Origin' && merged.element && !['air', 'earth', 'fire', 'lightning', 'water'].includes(String(merged.element).toLowerCase())) return 'Choose a valid elemental origin.'; if ('backgroundAnswers' in changes && (!Array.isArray(changes.backgroundAnswers) || changes.backgroundAnswers.length > 3 || changes.backgroundAnswers.some(item => !item || typeof item.answer !== 'string' || item.answer.length > 2000))) return 'Background answers must be up to three text responses.'; if ('connectionAnswers' in changes && (!Array.isArray(changes.connectionAnswers) || changes.connectionAnswers.length > 3 || changes.connectionAnswers.some(item => !item || typeof item.answer !== 'string' || item.answer.length > 2000))) return 'Connection answers must be up to three text responses.';
  if (merged.complete === true && (!merged.name?.trim() || !classNames.has(merged.className) || !ancestryNames.has(merged.ancestry) || !communityNames.has(merged.community) || !subclassFor(merged.className, merged.subclassName) || !cardFor(merged.armorName, equipment.armor || []) || !validTraitDistribution(merged.traits) || !Array.isArray(merged.experiences) || merged.experiences.length !== 2 || merged.experiences.some(item => !item || !String(item.text || '').trim()) || !Array.isArray(merged.domainCards) || merged.domainCards.length < 2 || merged.domainCards.length > Math.min(11, Number(merged.level || 1) + 1) || merged.domainCards.filter(item => typeof item === 'object' && item && !item.inVault).length > 5 || (Array.isArray(merged.domainCards) && merged.domainCards.some(item => !validDomainCard(item, merged.className, merged.level))) || (merged.className === 'Druid' && !merged.beastformName) || (merged.className === 'Ranger' && merged.subclassName === 'Beastbound' && !merged.companion?.name) || (merged.className === 'Sorcerer' && merged.subclassName === 'Elemental Origin' && !merged.element))) return 'A complete character needs identity, heritage, class, subclass, armor, valid domain cards, all six traits, and any required class-specific configuration.';
  return null;
}

function applyDerivedValues(character, changes) {
  const merged = { ...character, ...changes }; const selectedClass = cardFor(merged.className, classes); const subclass = subclassFor(merged.className, merged.subclassName); const ancestry = cardFor(merged.ancestry, ancestries); const community = cardFor(merged.community, communities); const armor = cardFor(merged.armorName, equipment.armor || []); const primary = cardFor(merged.primaryWeapon?.name || merged.primaryWeapon, equipment.weapons || []); const secondary = cardFor(merged.secondaryWeapon?.name || merged.secondaryWeapon, equipment.weapons || []); const modifiers = armorModifiers(armor); const next = { ...changes };
  if (('className' in changes || 'ancestry' in changes) && selectedClass?.stats?.hp !== undefined) next.hpMax = selectedClass.stats.hp + ((ancestry?.features || []).some(feature => /additional Hit Point slot/i.test(String(feature))) ? 1 : 0);
  if ('className' in changes || 'subclassName' in changes || 'ancestry' in changes || 'community' in changes) { next.ancestryCard = ancestry || null; next.communityCard = community || null; next.ancestryFeatures = ancestry?.features || []; next.communityFeatures = community?.features || []; next.classFeatures = [...(selectedClass?.classFeatures || []), ...unlockedSubclassFeatures(subclass, merged.level)]; next.classBackgroundQuestions = selectedClass?.backgroundQuestions || []; next.classConnectionQuestions = selectedClass?.connectionQuestions || []; Object.assign(next, specializedFor(merged, merged.className)); }
  if (('className' in changes || 'subclassName' in changes || 'armorName' in changes || 'level' in changes) && !('evasion' in changes) && selectedClass?.stats?.evasion !== undefined) next.evasion = selectedClass.stats.evasion + modifiers.evasion;
  if ('armorName' in changes && armor) { next.armor = armor.score; next.armorScore = armor.score; next.armorFeature = armor.feature || ''; next.armorSlots = Array.from({ length: armor.score }, (_, index) => ({ id: index + 1, marked: Boolean(character.armorSlots?.[index]?.marked) })); next.majorThreshold = armor.minor + Number(merged.level || 1) + thresholdBonusFor(subclass, merged.level); next.severeThreshold = armor.major + Number(merged.level || 1) + thresholdBonusFor(subclass, merged.level); }
  if ('armorName' in changes && !armor) { next.armor = 0; next.armorScore = 0; next.armorFeature = ''; next.armorSlots = []; next.majorThreshold = null; next.severeThreshold = null; }
  if (('level' in changes || 'subclassName' in changes) && armor) { next.majorThreshold = armor.minor + Number(merged.level || 1) + thresholdBonusFor(subclass, merged.level); next.severeThreshold = armor.major + Number(merged.level || 1) + thresholdBonusFor(subclass, merged.level); }
  if ('armorName' in changes || 'primaryWeapon' in changes || 'secondaryWeapon' in changes) next.inventory = Array.from(new Set([...(character.inventory || []), armor?.name, primary?.name, secondary?.name].filter(Boolean))).slice(0, 50);
  if ('armor' in changes && !('armorScore' in changes) && !('armorName' in changes)) next.armorScore = Number(changes.armor);
  return next;
}

module.exports = { buildCharacterFromChoices, validateCharacterModel, applyDerivedValues, emptyTraits };
