const http = require('http');
const https = require('https');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { buildCharacterFromChoices, validateCharacterModel, applyDerivedValues } = require('./character-model');
const { createPostgresStore } = require('./postgres-store');
const { uploadAvatar, uploadBackup, signedObjectUrl } = require('./object-storage');

function readJson(file, fallback) { try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return fallback; } }
function readJsonDirectory(directory) { if (!fs.existsSync(directory)) return []; return fs.readdirSync(directory).filter(name => name.endsWith('.json')).flatMap(name => { const value = readJson(path.join(directory, name), []); return Array.isArray(value) ? value : []; }); }
const contentRoot = path.join(process.cwd(), 'src', 'content', 'daggerforge');
const baseLibrary = {
  adversaries: readJsonDirectory(path.join(contentRoot, 'adversaries')),
  environments: readJsonDirectory(path.join(contentRoot, 'environments')),
  items: readJson(path.join(contentRoot, 'srd', 'items.json'), []),
};
function clone(value) { return JSON.parse(JSON.stringify(value)); }
function libraryEntries(campaign, type, includeArchived = false) { const base = (baseLibrary[type] || []).map(entry => ({ ...clone(entry), source: entry.source || 'daggerforge', editable: false })); const custom = ((campaign.gmLibrary && campaign.gmLibrary[type]) || []).filter(entry => includeArchived || !entry.archivedAt).map(entry => ({ ...clone(entry), source: 'custom', editable: true })); return [...custom, ...base]; }
function normalizeAdversary(raw) { const value = raw && typeof raw === 'object' ? raw : {}; const hpMax = Math.max(0, Number(value.hpMax ?? value.hp ?? 0) || 0); return { id: id(), sourceId: String(value.sourceId || value.id || ''), name: String(value.name || 'Adversary').slice(0, 120), tier: String(value.tier || ''), hp: hpMax, hpMax, stress: Math.max(0, Number(value.stress || 0) || 0), defeated: false, data: clone(value.data || value) }; }
function normalizeTemplate(body, existing) { const value = body && typeof body === 'object' ? body : {}; const template = existing || {}; const adversaries = Array.isArray(value.adversaries) ? value.adversaries.slice(0, 50).map(a => ({ sourceId: String(a.sourceId || a.id || ''), name: String(a.name || 'Adversary').slice(0, 120), tier: String(a.tier || ''), hpMax: Math.max(0, Number(a.hpMax ?? a.hp ?? 0) || 0), count: Math.max(1, Math.min(20, Number(a.count || 1) || 1)), data: clone(a.data || a) })) : (template.adversaries || []);
  return { ...template, name: String(value.name ?? template.name ?? 'Untitled Encounter').slice(0, 120), description: String(value.description ?? template.description ?? '').slice(0, 4000), environment: String(value.environment ?? template.environment ?? '').slice(0, 120), environmentData: value.environmentData && typeof value.environmentData === 'object' ? clone(value.environmentData) : (template.environmentData || {}), adversaries, notes: String(value.notes ?? template.notes ?? '').slice(0, 4000) };
}

function validateLibraryContent(type, data) {
  if (!data || typeof data !== 'object' || Array.isArray(data)) return 'Library content must be an object.';
  const name = String(data.name || '').trim();
  if (!name) return 'A name is required.';
  if (name.length > 120) return 'Name must be 120 characters or fewer.';
  if (type === 'adversaries') {
    if (!String(data.hp ?? '').trim() || !Number.isFinite(Number(data.hp)) || Number(data.hp) < 0) return 'Adversaries need a valid non-negative HP value.';
    if (data.features !== undefined && !Array.isArray(data.features)) return 'Adversary features must be a list.';
  }
  if (type === 'environments' && String(data.description || '').length > 4000) return 'Environment description must be 4,000 characters or fewer.';
  if (type === 'items' && String(data.description || data.text || '').length > 4000) return 'Item description must be 4,000 characters or fewer.';
  return null;
}
function validateEncounterTemplate(body) {
  if (!body || typeof body !== 'object') return 'Encounter template must be an object.';
  if (!String(body.name || '').trim()) return 'Encounter template name is required.';
  if (String(body.name).length > 120) return 'Encounter template name must be 120 characters or fewer.';
  if (!Array.isArray(body.adversaries) || body.adversaries.length > 50) return 'An encounter template must contain at most 50 adversaries.';
  if (body.adversaries.some(adversary => !adversary || !String(adversary.name || '').trim() || !Number.isFinite(Number(adversary.hpMax)) || Number(adversary.hpMax) < 0 || (adversary.count !== undefined && (!Number.isInteger(Number(adversary.count)) || Number(adversary.count) < 1 || Number(adversary.count) > 20)))) return 'Every template adversary needs a name, valid HP, and a count from 1 to 20.';
  return null;
}

const port = Number(process.env.PORT || 8787);
const dataDir = path.join(process.cwd(), 'data');
const dbFile = path.join(dataDir, 'campaigns.json');
const avatarDir = path.join(dataDir, 'avatars');
const backupDir = path.join(dataDir, 'backups');
const logDir = path.join(dataDir, 'logs');
fs.mkdirSync(dataDir, { recursive: true });
fs.mkdirSync(avatarDir, { recursive: true });
fs.mkdirSync(backupDir, { recursive: true });
fs.mkdirSync(logDir, { recursive: true });

function load() {
  if (!fs.existsSync(dbFile)) return { campaigns: {}, participants: {}, events: [] };
  try { return JSON.parse(fs.readFileSync(dbFile, 'utf8')); } catch { return { campaigns: {}, participants: {}, events: [] }; }
}
let db = load(); db.sessions = db.sessions || {};
const postgres = createPostgresStore();
const metrics = { requests: 0, errors: 0, backups: 0, startedAt: Date.now(), responses: {} };
function sendSentry(record) { if (!process.env.SENTRY_DSN) return; try { const dsn = new URL(process.env.SENTRY_DSN); const project = dsn.pathname.replace(/^\//, ''); if (!dsn.username || !project) return; const eventId = crypto.randomUUID().replace(/-/g, ''); const envelope = `${JSON.stringify({ event_id: eventId, sentry_version: '7', sdk: { name: 'daggerforge-server', version: '1.0.0' } })}\n${JSON.stringify({ type: 'event' })}\n${JSON.stringify({ event_id: eventId, timestamp: Date.now() / 1000, level: record.level === 'security' ? 'warning' : 'error', message: record.event, extra: record })}`; const request = https.request(`https://${dsn.host}/api/${project}/envelope/?sentry_version=7&sentry_key=${encodeURIComponent(dsn.username)}`, { method: 'POST', headers: { 'content-type': 'application/x-sentry-envelope', 'content-length': Buffer.byteLength(envelope) } }, response => response.resume()); request.on('error', () => {}); request.end(envelope); } catch {} }
function structuredLog(level, event, fields = {}) { const record = { timestamp: now(), level, event, ...fields }; try { fs.appendFileSync(path.join(logDir, 'api.jsonl'), JSON.stringify(record) + '\n'); } catch {} if (level === 'error' || level === 'security') sendSentry(record); const webhook = process.env.LOG_AGGREGATION_WEBHOOK; if (webhook && (level === 'error' || level === 'security')) { try { const url = new URL(webhook); const body = JSON.stringify(record); const request = https.request(url, { method: 'POST', headers: { 'content-type': 'application/json', 'content-length': Buffer.byteLength(body) } }, response => response.resume()); request.on('error', () => {}); request.end(body); } catch {} } if (level === 'error' || level === 'security') console.error(JSON.stringify(record)); }
function save() { if (!postgres || process.env.WRITE_LOCAL_MIRROR === '1') { const tmp = `${dbFile}.tmp`; fs.writeFileSync(tmp, JSON.stringify(db, null, 2)); fs.renameSync(tmp, dbFile); } if (postgres) postgres.persist(db).catch(error => console.error(`Postgres persistence failed: ${error.message}`)); }
async function backupSnapshot(campaignId) { const stamp = new Date().toISOString().replace(/[:.]/g, '-'); const campaigns = Object.values(db.campaigns).filter(campaign => !campaignId || campaign.id === campaignId).map(campaign => { const copy = clone(campaign); delete copy.gmTokenHash; delete copy.playerTokenHash; return copy; }); const participants = Object.values(db.participants).filter(participant => !campaignId || participant.campaignId === campaignId).map(participant => { const copy = { ...participant }; delete copy.tokenHash; return copy; }); const snapshot = campaignId ? { schemaVersion: 1, exportedAt: now(), campaign: campaigns[0] || null, participants } : { schemaVersion: 1, exportedAt: now(), campaigns, participants }; const payload = Buffer.from(JSON.stringify(snapshot, null, 2)); const filename = `daggerforge-${stamp}.json`; const target = path.join(backupDir, filename); fs.writeFileSync(target, payload); const remote = await uploadBackup(filename, payload); const retention = Math.max(1, Number(process.env.BACKUP_RETENTION || 14)); const files = fs.readdirSync(backupDir).filter(name => name.endsWith('.json')).sort().reverse(); files.slice(retention).forEach(name => fs.unlinkSync(path.join(backupDir, name))); metrics.backups += 1; return { file: target, remote: remote || null, campaigns: campaigns.length, createdAt: snapshot.exportedAt, name: filename }; }
function id() { return crypto.randomUUID(); }
function token() { return crypto.randomBytes(32).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, ''); }
function hash(value) { return crypto.createHash('sha256').update(value).digest('hex'); }
function now() { return new Date().toISOString(); }
function json(res, status, value) { const body = JSON.stringify(value); res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', 'content-length': Buffer.byteLength(body) }); res.end(body); }
function error(res, status, message) { json(res, status, { error: message }); }
function readBody(req) { return new Promise((resolve, reject) => { let raw = ''; req.on('data', chunk => { raw += chunk; if (raw.length > 1_000_000) req.destroy(); }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('Invalid JSON')); } }); req.on('error', reject); }); }
function bearer(req) { const value = req.headers.authorization || ''; return value.startsWith('Bearer ') ? value.slice(7) : ''; }
function cookies(req) { return Object.fromEntries(String(req.headers.cookie || '').split(';').map(x => x.trim().split('=').map(decodeURIComponent)).filter(x => x.length === 2)); }
function cookieHeader(value, maxAge) { return `df_session=${encodeURIComponent(value)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${maxAge}${process.env.NODE_ENV === 'production' ? '; Secure' : ''}`; }
function sessionActor(req, campaignId) { const sessionId = cookies(req).df_session; const session = sessionId && db.sessions[hash(sessionId)]; if (!session || session.expiresAt < Date.now() || session.campaignId !== campaignId) return null; return { role: session.role, id: session.actorId }; }
function findAccess(campaign, raw) { if (!raw) return null; const digest = hash(raw); if (digest === campaign.gmTokenHash) return { role: 'GM', id: 'gm' }; if (digest === campaign.playerTokenHash) return { role: 'JOIN', id: 'join' }; const participant = Object.values(db.participants).find(p => p.campaignId === campaign.id && p.tokenHash === digest && !p.revoked); return participant ? { role: 'PLAYER', id: participant.id } : null; }
const streams = new Map();
const attempts = new Map();
async function rateLimited(key, max = Number(process.env.RATE_LIMIT_MAX || 120), windowMs = Number(process.env.RATE_LIMIT_WINDOW_MS || 60_000)) { if (postgres) { try { return await postgres.consumeRateLimit(key, max, windowMs); } catch (error) { structuredLog('error', 'shared_rate_limit_failed', { error: error.message }); } } const current = attempts.get(key) || { count: 0, started: Date.now() }; if (Date.now() - current.started > windowMs) { attempts.set(key, { count: 1, started: Date.now() }); return false; } current.count += 1; attempts.set(key, current); if (attempts.size > 10_000) for (const [entryKey, entry] of attempts) if (Date.now() - entry.started > windowMs) attempts.delete(entryKey); return current.count > max; }
function safeEventForPlayer(event) {
  const safe = { ...event, previousValue: undefined };
  delete safe.undoPreviousValue; delete safe.undoNewValue;
  if (event.entityType === 'campaign' && event.field === 'mode') safe.newValue = event.newValue;
  else if (event.entityType === 'session') safe.newValue = event.newValue && typeof event.newValue === 'object' ? { status: event.newValue.status, title: event.newValue.title } : { changed: true };
  else safe.newValue = { changed: true };
  return safe;
}
function auditValue(value, entityType) { if (entityType !== 'character' || !value || typeof value !== 'object') return value; if (Array.isArray(value)) return value.map(item => auditValue(item, entityType)); const copy = { ...value }; delete copy.privateNotes; return copy; }
function eventForClient(event, role) { const copy = { ...event }; delete copy.undoPreviousValue; delete copy.undoNewValue; return role === 'PLAYER' ? safeEventForPlayer(copy) : copy; }
function publish(campaignId, event) { const listeners = streams.get(campaignId) || []; listeners.forEach(listener => { listener.res.write(`data: ${JSON.stringify(eventForClient(event, listener.role))}\n\n`); }); }
function audit(campaign, actor, operation, entityType, entityId, field, before, after) { const currentSession = (campaign.sessions || []).find(session => session.status === 'ACTIVE'); const event = { id: id(), campaignId: campaign.id, actorId: actor.id, actorRole: actor.role, actorLabel: actor.role === 'PLAYER' ? (db.participants[actor.id]?.nickname || 'Player') : 'GM', sessionId: currentSession?.id || null, operation, entityType, entityId, field, previousValue: auditValue(before, entityType), newValue: auditValue(after, entityType), undoPreviousValue: before, undoNewValue: after, createdAt: now() }; db.events.unshift(event); publish(campaign.id, event); }
function validateCharacterChanges(character, changes) { const numeric = [['hp', 0, Number(character.hpMax || 0)], ['hpMax', 1, 24], ['hope', 0, 6], ['stress', 0, 6], ['armor', 0, 12], ['level', 1, 10]]; for (const [key, min, max] of numeric) if (Object.prototype.hasOwnProperty.call(changes, key) && (!Number.isInteger(Number(changes[key])) || Number(changes[key]) < min || Number(changes[key]) > max)) return `${key} must be an integer between ${min} and ${max}.`; if (Object.prototype.hasOwnProperty.call(changes, 'hpMax') && Number(changes.hpMax) < Number(character.hp || 0)) return 'HP maximum cannot be lower than current HP.'; return null; }
function publicCharacter(c, includePrivate) { const copy = { ...c }; delete copy.lastFieldVersions; if (!includePrivate) delete copy.privateNotes; return copy; }
function view(campaign, actor) { const chars = Object.values(campaign.characters).map(c => { if (actor.role !== 'GM' && c.ownerId === actor.id) return publicCharacter(c, true); if (actor.role === 'GM') return publicCharacter(c, false); return { id: c.id, name: c.name, className: c.className, ancestry: c.ancestry, color: c.color, initials: c.initials, complete: c.complete, assigned: Boolean(c.ownerId) }; }); const sessions = actor.role === 'GM' ? (campaign.sessions || []) : (campaign.sessions || []).map(({ notes, ...session }) => session); const encounters = actor.role === 'GM' ? (campaign.encounters || []) : (campaign.encounters || []).map(encounter => ({ id: encounter.id, name: encounter.name, environment: encounter.environment, status: encounter.status, adversaries: (encounter.adversaries || []).map(({ id, name, hp, hpMax, defeated }) => ({ id, name, hp, hpMax, defeated })) })); const out = { id: campaign.id, name: campaign.name, mode: campaign.mode, joinEnabled: campaign.joinEnabled, characters: chars, announcements: campaign.announcements || [], sessions, encounters }; if (actor.role === 'GM') { out.gmLibrary = campaign.gmLibrary; out.encounterTemplates = campaign.encounterTemplates || []; out.participants = Object.values(db.participants).filter(participant => participant.campaignId === campaign.id).map(({ id, nickname, characterId, revoked, createdAt }) => ({ id, nickname, characterId, revoked, createdAt })); out.events = db.events.filter(e => e.campaignId === campaign.id).slice(0, 100).map(event => eventForClient(event, 'GM')); } return out; }
function presenceFor(campaign, actor) { campaign.presence = campaign.presence || {}; const cutoff = Date.now() - 45_000; Object.keys(campaign.presence).forEach(k => { if (new Date(campaign.presence[k].lastSeen).getTime() < cutoff) delete campaign.presence[k]; }); const active = Object.values(campaign.presence); if (actor.role !== 'GM') return { count: active.length }; return active.map((entry) => { const participant = db.participants[entry.participantId]; return { participantId: entry.participantId, role: entry.role, nickname: participant?.nickname || 'Participant', characterId: participant?.characterId || null, lastSeen: entry.lastSeen }; }); }

async function route(req, res) {
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
  const parts = url.pathname.split('/').filter(Boolean);
  try {
    if (req.method === 'GET' && url.pathname === '/health') { let persistence = { provider: 'local-json', ok: true }; if (postgres) { try { persistence = await postgres.health(); } catch (error) { persistence = { provider: 'postgres', ok: false, error: error.message }; } } return json(res, persistence.ok ? 200 : 503, { ok: persistence.ok, time: now(), uptimeSeconds: Math.floor((Date.now() - metrics.startedAt) / 1000), persistence, backups: fs.readdirSync(backupDir).filter(name => name.endsWith('.json')).length }); }
    if (req.method === 'GET' && url.pathname === '/metrics') { const responseLines = Object.entries(metrics.responses).map(([status, count]) => `daggerforge_responses_total{status="${status}"} ${count}`); const body = [`daggerforge_requests_total ${metrics.requests}`, `daggerforge_errors_total ${metrics.errors}`, `daggerforge_backups_total ${metrics.backups}`, `daggerforge_uptime_seconds ${Math.floor((Date.now() - metrics.startedAt) / 1000)}`, ...responseLines].join('\n') + '\n'; res.writeHead(200, { 'content-type': 'text/plain; version=0.0.4', 'cache-control': 'no-store' }); return res.end(body); }
    if (req.method === 'POST' && url.pathname === '/api/campaigns') {
      const body = await readBody(req); const gmToken = token(); const playerToken = token(); const campaign = { id: id(), name: String(body.name || 'Untitled Campaign').slice(0, 120), mode: 'PREPARATION', joinEnabled: true, gmTokenHash: hash(gmToken), playerTokenHash: hash(playerToken), createdAt: now(), characters: {}, gmLibrary: { adversaries: [], environments: [], items: [], encounters: [] }, encounterTemplates: [] };
      db.campaigns[campaign.id] = campaign; save(); return json(res, 201, { campaign: { id: campaign.id, name: campaign.name, mode: campaign.mode }, gmToken, playerToken });
    }
    if (req.method === 'POST' && url.pathname === '/api/session') { const body = await readBody(req); const campaign = db.campaigns[body.campaignId]; const actor = campaign && findAccess(campaign, String(body.accessToken || '')); if (!campaign || !actor || actor.role === 'JOIN') return error(res, 401, 'Invalid access credentials.'); const sessionId = token(); db.sessions[hash(sessionId)] = { campaignId: campaign.id, actorId: actor.id, role: actor.role, expiresAt: Date.now() + 30 * 24 * 60 * 60 * 1000 }; save(); res.setHeader('set-cookie', cookieHeader(sessionId, 30 * 24 * 60 * 60)); return json(res, 200, { ok: true, role: actor.role, campaignId: campaign.id }); }
    if (req.method === 'POST' && url.pathname === '/api/session/logout') { const sessionId = cookies(req).df_session; if (sessionId) delete db.sessions[hash(sessionId)]; save(); res.setHeader('set-cookie', cookieHeader('', 0)); return json(res, 200, { ok: true }); }
    if (req.method === 'POST' && url.pathname === '/api/campaigns/import') {
      const body = await readBody(req); const source = body && body.campaign; if (!source || body.schemaVersion !== 1 || typeof source.name !== 'string' || typeof source.characters !== 'object') return error(res, 400, 'Unsupported or incomplete export format.');
      const gmToken = token(); const playerToken = token(); const campaign = { id: id(), name: String(source.name || 'Imported Campaign').slice(0, 120), mode: source.mode === 'PLAY' ? 'PLAY' : 'PREPARATION', joinEnabled: source.joinEnabled !== false, gmTokenHash: hash(gmToken), playerTokenHash: hash(playerToken), createdAt: now(), characters: {}, gmLibrary: source.gmLibrary && typeof source.gmLibrary === 'object' ? source.gmLibrary : { adversaries: [], environments: [], items: [], encounters: [] }, encounterTemplates: Array.isArray(source.encounterTemplates) ? source.encounterTemplates : [] };
      const sourceCharacters = source.characters && typeof source.characters === 'object' ? source.characters : {};
      const characterIdMap = {}; Object.entries(sourceCharacters).slice(0, 100).forEach(([oldId, raw]) => { const character = raw && typeof raw === 'object' ? raw : {}; const characterId = id(); characterIdMap[oldId] = characterId; campaign.characters[characterId] = { id: characterId, name: String(character.name || 'Imported Character').slice(0, 120), className: String(character.className || ''), ancestry: String(character.ancestry || ''), color: String(character.color || '#a88be3'), initials: String(character.initials || 'PC').slice(0, 4), hp: Number.isFinite(character.hp) ? character.hp : 0, hpMax: Number.isFinite(character.hpMax) ? character.hpMax : 6, hope: Number.isFinite(character.hope) ? character.hope : 0, stress: Number.isFinite(character.stress) ? character.stress : 0, armor: Number.isFinite(character.armor) ? character.armor : 0, level: Number.isFinite(character.level) ? character.level : 1, complete: character.complete === true, ownerId: null, inventory: Array.isArray(character.inventory) ? character.inventory.slice(0, 50).map(String) : [], privateNotes: '', version: 1 }; });
      const importedParticipants = []; const sourceParticipants = Array.isArray(body.participants) ? body.participants : []; sourceParticipants.slice(0, 100).forEach(raw => { const participant = raw && typeof raw === 'object' ? raw : {}; const participantId = id(); const participantToken = token(); const mappedCharacterId = participant.characterId && characterIdMap[participant.characterId] ? characterIdMap[participant.characterId] : null; db.participants[participantId] = { id: participantId, campaignId: campaign.id, nickname: String(participant.nickname || 'Imported Player').slice(0, 60), tokenHash: hash(participantToken), revoked: participant.revoked === true, characterId: mappedCharacterId, createdAt: now() }; if (mappedCharacterId) campaign.characters[mappedCharacterId].ownerId = participantId; importedParticipants.push({ id: participantId, nickname: db.participants[participantId].nickname, characterId: mappedCharacterId, participantToken, revoked: db.participants[participantId].revoked }); });
      db.campaigns[campaign.id] = campaign; save(); return json(res, 201, { campaign: { id: campaign.id, name: campaign.name, mode: campaign.mode }, gmToken, playerToken, importedCharacters: Object.keys(campaign.characters).length, importedParticipants });
    }
    if (parts[0] !== 'api' || parts[1] !== 'campaigns' || !parts[2]) return error(res, 404, 'Not found');
    const campaign = db.campaigns[parts[2]]; if (!campaign) return error(res, 404, 'Not found');
    const actor = findAccess(campaign, bearer(req)) || sessionActor(req, campaign.id); if (!actor || (actor.role === 'JOIN' && !(req.method === 'POST' && parts[3] === 'join'))) { structuredLog('security', 'authorization_denied', { method: req.method, path: url.pathname, campaignId: campaign.id }); return error(res, 404, 'Not found'); }
    if (campaign.archivedAt && !(req.method === 'GET' || req.method === 'DELETE' || parts[3] === 'export')) return error(res, 410, 'Campaign is archived.');
    if (req.method === 'GET' && parts.length === 3) return json(res, 200, view(campaign, actor));
    if (req.method === 'POST' && parts[3] === 'backup') { if (actor.role !== 'GM') return error(res, 404, 'Not found'); return json(res, 201, await backupSnapshot(campaign.id)); }
    if (req.method === 'GET' && parts[3] === 'backups' && !parts[4]) { if (actor.role !== 'GM') return error(res, 404, 'Not found'); const backups = fs.readdirSync(backupDir).filter(name => name.endsWith('.json')).sort().reverse().map(name => ({ name, createdAt: fs.statSync(path.join(backupDir, name)).mtime.toISOString(), sizeBytes: fs.statSync(path.join(backupDir, name)).size })); return json(res, 200, { backups }); }
    if (req.method === 'GET' && parts[3] === 'backups' && parts[4]) { if (actor.role !== 'GM') return error(res, 404, 'Not found'); const filename = path.basename(parts[4]); const target = path.join(backupDir, filename); if (fs.existsSync(target)) return json(res, 200, JSON.parse(fs.readFileSync(target, 'utf8'))); const signed = await signedObjectUrl(`storage://${process.env.SUPABASE_BACKUP_BUCKET || 'backups'}/${filename}`); if (signed) { res.writeHead(302, { location: signed, 'cache-control': 'private, max-age=60' }); return res.end(); } return error(res, 404, 'Backup not found'); }
    if (req.method === 'GET' && parts[3] === 'content') { if (actor.role !== 'GM') return error(res, 404, 'Not found'); const requested = url.searchParams.get('type'); const includeArchived = url.searchParams.get('includeArchived') === '1'; const types = requested && ['adversaries', 'environments', 'items'].includes(requested) ? [requested] : ['adversaries', 'environments', 'items']; return json(res, 200, { content: Object.fromEntries(types.map(type => [type, libraryEntries(campaign, type, includeArchived)])) }); }
    if (req.method === 'GET' && parts[3] === 'presence') return json(res, 200, { presence: presenceFor(campaign, actor) });
    if (req.method === 'POST' && parts[3] === 'presence') { campaign.presence = campaign.presence || {}; campaign.presence[actor.id] = { participantId: actor.id, role: actor.role, lastSeen: now() }; save(); return json(res, 200, { presence: presenceFor(campaign, actor) }); }
    if (req.method === 'POST' && parts[3] === 'archive') { if (actor.role !== 'GM') return error(res, 404, 'Not found'); campaign.archivedAt = now(); audit(campaign, actor, 'campaign.archive', 'campaign', campaign.id, 'archivedAt', null, campaign.archivedAt); save(); return json(res, 200, { archived: true, archivedAt: campaign.archivedAt }); }
    if (req.method === 'DELETE' && parts.length === 3) { if (actor.role !== 'GM') return error(res, 404, 'Not found'); const body = await readBody(req); if (body.confirmName !== campaign.name || body.confirmText !== 'DELETE CAMPAIGN') return error(res, 400, 'Type the campaign name and DELETE CAMPAIGN to confirm.'); delete db.campaigns[campaign.id]; Object.keys(db.participants).forEach(k => { if (db.participants[k].campaignId === campaign.id) delete db.participants[k]; }); db.events = db.events.filter(e => e.campaignId !== campaign.id); save(); return json(res, 200, { deleted: true }); }
    if (req.method === 'GET' && parts[3] === 'events') { const limit = Math.min(100, Math.max(1, Number(url.searchParams.get('limit') || 50))); const offset = Math.max(0, Number(url.searchParams.get('offset') || 0)); const operation = url.searchParams.get('operation'); const entityType = url.searchParams.get('entityType'); const actorId = url.searchParams.get('actorId'); const entityId = url.searchParams.get('entityId'); const sessionId = url.searchParams.get('sessionId'); const from = url.searchParams.get('from'); const to = url.searchParams.get('to'); const campaignEvents = db.events.filter(e => e.campaignId === campaign.id); const all = campaignEvents.filter(e => !operation || e.operation === operation).filter(e => !entityType || e.entityType === entityType).filter(e => !actorId || e.actorId === actorId).filter(e => !entityId || e.entityId === entityId).filter(e => !sessionId || e.sessionId === sessionId).filter(e => !from || e.createdAt >= from).filter(e => !to || e.createdAt <= to); const events = all.slice(offset, offset + limit).map(event => eventForClient(event, actor.role)); const actorMap = new Map(campaignEvents.map(event => [event.actorId, event.actorLabel || event.actorRole || 'Actor'])); return json(res, 200, { events, nextOffset: offset + events.length < all.length ? offset + events.length : null, total: all.length, metadata: { actors: Array.from(actorMap, ([id, label]) => ({ id, label })), entityTypes: Array.from(new Set(campaignEvents.map(event => event.entityType).filter(Boolean))), operations: Array.from(new Set(campaignEvents.map(event => event.operation).filter(Boolean))), sessions: (campaign.sessions || []).map(session => ({ id: session.id, title: session.title || 'Untitled session' })) } }); }
    if (req.method === 'GET' && parts[3] === 'stream') {
      res.writeHead(200, { 'content-type': 'text/event-stream', 'cache-control': 'no-cache', connection: 'keep-alive' }); res.write(`data: ${JSON.stringify({ type: 'connected' })}\n\n`); const list = streams.get(campaign.id) || []; const listener = { res, role: actor.role, id: actor.id }; list.push(listener); streams.set(campaign.id, list); req.on('close', () => streams.set(campaign.id, (streams.get(campaign.id) || []).filter(x => x !== listener))); return;
    }
    if (req.method === 'POST' && parts[3] === 'join') {
      if (actor.role !== 'GM' && actor.role !== 'JOIN') return error(res, 404, 'Not found');
      if (!campaign.joinEnabled) return error(res, 403, 'New player joins are disabled.'); const body = await readBody(req); const participantToken = token(); const participant = { id: id(), campaignId: campaign.id, nickname: String(body.nickname || 'Player').slice(0, 60), tokenHash: hash(participantToken), revoked: false, characterId: null, createdAt: now() }; db.participants[participant.id] = participant; save(); return json(res, 201, { participant: { id: participant.id, nickname: participant.nickname }, participantToken, campaign: view(campaign, { role: 'PLAYER', id: participant.id }) });
    }
    if (req.method === 'POST' && parts[3] === 'mode') { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const body = await readBody(req); const before = campaign.mode; campaign.mode = body.mode === 'PLAY' ? 'PLAY' : 'PREPARATION'; save(); audit(campaign, actor, 'mode.change', 'campaign', campaign.id, 'mode', before, campaign.mode); save(); return json(res, 200, view(campaign, actor)); }
    if (req.method === 'POST' && parts[3] === 'sessions') { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const body = await readBody(req); const session = { id: id(), title: String(body.title || 'Untitled Session').slice(0, 120), notes: String(body.notes || '').slice(0, 4000), status: 'ACTIVE', startedAt: now(), endedAt: null }; campaign.sessions = campaign.sessions || []; campaign.sessions.unshift(session); audit(campaign, actor, 'session.start', 'session', session.id, 'status', null, 'ACTIVE'); save(); return json(res, 201, session); }
    if (req.method === 'PATCH' && parts[3] === 'sessions' && parts[4]) { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const session = (campaign.sessions || []).find(s => s.id === parts[4]); if (!session) return error(res, 404, 'Not found'); const body = await readBody(req); const before = { status: session.status, title: session.title, notes: session.notes }; if (body.status === 'ENDED') { session.status = 'ENDED'; session.endedAt = now(); } if (typeof body.title === 'string' && body.title.trim()) session.title = body.title.trim().slice(0, 120); if (typeof body.notes === 'string') session.notes = body.notes.slice(0, 4000); audit(campaign, actor, 'session.update', 'session', session.id, 'state', before, { status: session.status, title: session.title, notes: session.notes }); save(); return json(res, 200, session); }
    if (req.method === 'GET' && parts[3] === 'encounter-templates') { if (actor.role !== 'GM') return error(res, 404, 'Not found'); return json(res, 200, { templates: campaign.encounterTemplates || [] }); }
    if (req.method === 'POST' && parts[3] === 'encounter-templates') { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const body = await readBody(req); const templateError = validateEncounterTemplate(body); if (templateError) return error(res, 400, templateError); const template = { id: id(), ...normalizeTemplate(body), createdAt: now(), updatedAt: now() }; campaign.encounterTemplates = campaign.encounterTemplates || []; campaign.encounterTemplates.unshift(template); audit(campaign, actor, 'encounter-template.create', 'encounter-template', template.id, null, null, template); save(); return json(res, 201, template); }
    if (req.method === 'PATCH' && parts[3] === 'encounter-templates' && parts[4]) { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const template = (campaign.encounterTemplates || []).find(x => x.id === parts[4]); if (!template) return error(res, 404, 'Not found'); const body = await readBody(req); const templateError = validateEncounterTemplate({ ...template, ...body, adversaries: body.adversaries ?? template.adversaries }); if (templateError) return error(res, 400, templateError); const before = clone(template); Object.assign(template, normalizeTemplate(body, template), { updatedAt: now() }); audit(campaign, actor, 'encounter-template.update', 'encounter-template', template.id, 'state', before, template); save(); return json(res, 200, template); }
    if (req.method === 'POST' && parts[3] === 'encounter-templates' && parts[4] && parts[5] === 'duplicate') { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const original = (campaign.encounterTemplates || []).find(x => x.id === parts[4]); if (!original) return error(res, 404, 'Not found'); const duplicate = { ...clone(original), id: id(), name: `${original.name} Copy`.slice(0, 120), createdAt: now(), updatedAt: now() }; campaign.encounterTemplates.unshift(duplicate); audit(campaign, actor, 'encounter-template.duplicate', 'encounter-template', duplicate.id, null, original.id, duplicate); save(); return json(res, 201, duplicate); }
    if (req.method === 'DELETE' && parts[3] === 'encounter-templates' && parts[4]) { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const index = (campaign.encounterTemplates || []).findIndex(x => x.id === parts[4]); if (index < 0) return error(res, 404, 'Not found'); const [removed] = campaign.encounterTemplates.splice(index, 1); audit(campaign, actor, 'encounter-template.delete', 'encounter-template', removed.id, null, removed, null); save(); return json(res, 200, { deleted: true }); }
    if (req.method === 'POST' && parts[3] === 'encounters') { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const body = await readBody(req); const template = body.templateId && (campaign.encounterTemplates || []).find(x => x.id === body.templateId); if (body.templateId && !template) return error(res, 404, 'Encounter template not found'); const source = template || normalizeTemplate(body); const encounter = { id: id(), templateId: template ? template.id : null, name: String(body.name || source.name || 'Untitled Encounter').slice(0, 120), environment: String(body.environment || source.environment || ''), environmentData: clone(body.environmentData || source.environmentData || {}), description: String(source.description || '').slice(0, 4000), status: 'ACTIVE', fear: Math.max(0, Math.min(99, Number(body.fear || 0))), adversaries: (Array.isArray(body.adversaries) ? body.adversaries : source.adversaries || []).flatMap(item => Array.from({ length: Math.max(1, Math.min(20, Number(item.count || 1))) }, () => item)).slice(0, 50).map(normalizeAdversary), createdAt: now() }; campaign.encounters = campaign.encounters || []; campaign.encounters.unshift(encounter); audit(campaign, actor, 'encounter.start', 'encounter', encounter.id, 'status', null, 'ACTIVE'); save(); return json(res, 201, encounter); }
    if (req.method === 'PATCH' && parts[3] === 'encounters' && parts[4]) { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const encounter = (campaign.encounters || []).find(e => e.id === parts[4]); if (!encounter) return error(res, 404, 'Not found'); const body = await readBody(req); if (body.status === 'ENDED') encounter.status = 'ENDED'; if (typeof body.name === 'string') encounter.name = body.name.slice(0, 120); if (typeof body.environment === 'string') encounter.environment = body.environment.slice(0, 120); if (typeof body.description === 'string') encounter.description = body.description.slice(0, 4000); if (body.environmentData && typeof body.environmentData === 'object') encounter.environmentData = clone(body.environmentData); if (Number.isFinite(Number(body.fear))) encounter.fear = Math.max(0, Math.min(99, Number(body.fear))); if (body.addAdversary && typeof body.addAdversary === 'object') encounter.adversaries.push(normalizeAdversary(body.addAdversary)); if (body.renameAdversary && typeof body.renameAdversary === 'object') { const rename = body.renameAdversary; const adv = encounter.adversaries.find(a => a.id === rename.adversaryId); if (!adv) return error(res, 404, 'Adversary not found'); const name = String(rename.name || '').trim(); if (!name || name.length > 120) return error(res, 400, 'Adversary name is required.'); adv.name = name; } if (body.removeAdversaryId) { const index = encounter.adversaries.findIndex(a => a.id === body.removeAdversaryId); if (index < 0) return error(res, 404, 'Adversary not found'); encounter.adversaries.splice(index, 1); } if (body.adversaryAction && typeof body.adversaryAction === 'object') { const action = body.adversaryAction; const adv = encounter.adversaries.find(a => a.id === action.adversaryId); if (!adv) return error(res, 404, 'Adversary not found'); const actionName = String(action.name || '').trim(); if (!actionName || actionName.length > 120) return error(res, 400, 'Choose a valid adversary action.'); audit(campaign, actor, 'encounter.adversary-action', 'encounter', encounter.id, 'adversaryAction', null, { adversaryId: adv.id, adversaryName: adv.name, name: actionName }); } if (body.adversaryId) { const adv = encounter.adversaries.find(a => a.id === body.adversaryId); if (!adv) return error(res, 404, 'Not found'); if (Number.isFinite(body.hp)) adv.hp = Math.max(0, Math.min(adv.hpMax, body.hp)); adv.defeated = adv.hp === 0; } audit(campaign, actor, 'encounter.update', 'encounter', encounter.id, 'state', null, encounter); save(); return json(res, 200, encounter); }
    if (req.method === 'GET' && parts[3] === 'participants') { if (actor.role !== 'GM') return error(res, 404, 'Not found'); return json(res, 200, { participants: Object.values(db.participants).filter(p => p.campaignId === campaign.id).map(p => ({ id: p.id, nickname: p.nickname, characterId: p.characterId, revoked: p.revoked, createdAt: p.createdAt })) }); }
    if (req.method === 'POST' && parts[3] === 'characters' && !parts[4]) { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const body = await readBody(req); const characterId = id(); campaign.characters[characterId] = buildCharacterFromChoices(body, characterId); const validationError = validateCharacterModel(campaign.characters[characterId], campaign.characters[characterId]); if (validationError) return error(res, 400, validationError); audit(campaign, actor, 'character.create', 'character', characterId, null, null, campaign.characters[characterId]); save(); return json(res, 201, publicCharacter(campaign.characters[characterId], true)); }
    if (req.method === 'PATCH' && parts[3] === 'participants' && parts[4] && !parts[5]) { const participant = db.participants[parts[4]]; if (!participant || participant.campaignId !== campaign.id || (actor.role !== 'GM' && actor.id !== participant.id)) return error(res, 404, 'Not found'); const body = await readBody(req); const before = participant.nickname; participant.nickname = String(body.nickname || before).slice(0, 60); audit(campaign, actor, 'participant.rename', 'participant', participant.id, 'nickname', before, participant.nickname); save(); return json(res, 200, { id: participant.id, nickname: participant.nickname }); }
    if (req.method === 'GET' && parts[3] === 'avatars' && parts[4]) { const character = campaign.characters[parts[4]]; if (!character || (actor.role === 'PLAYER' && character.ownerId !== actor.id)) return error(res, 404, 'Not found'); if (!character.avatarUrl) return error(res, 404, 'Avatar not found'); if (character.avatarUrl.startsWith('storage://')) { const signed = await signedObjectUrl(character.avatarUrl, 900); if (!signed) return error(res, 503, 'Avatar storage is unavailable.'); res.writeHead(302, { location: signed, 'cache-control': 'private, max-age=300' }); return res.end(); } const filename = path.basename(character.avatarUrl); const target = path.join(avatarDir, filename); if (!fs.existsSync(target)) return error(res, 404, 'Avatar not found'); res.writeHead(200, { 'content-type': filename.endsWith('.png') ? 'image/png' : filename.endsWith('.webp') ? 'image/webp' : 'image/jpeg', 'cache-control': 'private, max-age=300' }); return res.end(fs.readFileSync(target)); }
    if (req.method === 'POST' && parts[3] === 'avatars' && parts[4]) { const character = campaign.characters[parts[4]]; if (!character || (actor.role === 'PLAYER' && character.ownerId !== actor.id)) return error(res, 404, 'Not found'); const body = await readBody(req); const match = typeof body.dataUrl === 'string' ? body.dataUrl.match(/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/) : null; if (!match) return error(res, 400, 'Use a PNG, JPEG, or WebP image.'); const bytes = Buffer.from(match[2], 'base64'); if (bytes.length > 2_000_000) return error(res, 413, 'Avatar must be 2 MB or smaller.'); const extension = match[1].split('/')[1].replace('jpeg','jpg'); const filename = `${character.id}-${crypto.randomBytes(8).toString('hex')}.${extension}`; const remoteUrl = await uploadAvatar(filename, bytes, match[1]); if (!remoteUrl) fs.writeFileSync(path.join(avatarDir, filename), bytes); const before = character.avatarUrl || null; character.avatarUrl = remoteUrl || `/avatars/${filename}`; character.version += 1; audit(campaign, actor, 'avatar.replace', 'character', character.id, 'avatarUrl', before, character.avatarUrl); save(); return json(res, 200, { avatarUrl: remoteUrl ? `/api/campaigns/${campaign.id}/avatars/${character.id}` : character.avatarUrl, version: character.version, storage: remoteUrl ? 'supabase-private-signed' : 'local-development' }); }
    if (req.method === 'POST' && parts[3] === 'announcements') { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const body = await readBody(req); const announcement = { id: id(), text: String(body.text || '').slice(0, 500), createdAt: now(), actor: 'GM' }; campaign.announcements = campaign.announcements || []; campaign.announcements.unshift(announcement); audit(campaign, actor, 'announcement.create', 'announcement', announcement.id, 'text', null, announcement.text); save(); return json(res, 201, announcement); }
    if (req.method === 'POST' && parts[3] === 'library' && parts[4] && parts[5] && parts[6] === 'restore') { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const type = parts[4]; const entry = (campaign.gmLibrary[type] || []).find(item => item.id === parts[5]); if (!entry) return error(res, 404, 'Not found'); entry.archivedAt = null; entry.updatedAt = now(); audit(campaign, actor, 'library.restore', type, entry.id, 'archivedAt', true, null); save(); return json(res, 200, entry); }
    if (req.method === 'POST' && parts[3] === 'library') { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const body = await readBody(req); const type = ['adversaries','environments','items'].includes(body.type) ? body.type : 'items'; const validationError = validateLibraryContent(type, body.data); if (validationError) return error(res, 400, validationError); const entry = { id: id(), name: String(body.name || 'Untitled Content').slice(0, 120), source: 'custom', data: body.data && typeof body.data === 'object' ? clone(body.data) : {}, createdAt: now(), updatedAt: now(), archivedAt: null }; campaign.gmLibrary[type] = campaign.gmLibrary[type] || []; campaign.gmLibrary[type].unshift(entry); audit(campaign, actor, 'library.create', type, entry.id, null, null, entry); save(); return json(res, 201, entry); }
    if (req.method === 'PATCH' && parts[3] === 'library' && parts[4] && parts[5]) { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const type = parts[4]; if (!['adversaries','environments','items'].includes(type)) return error(res, 400, 'Unsupported content type'); const entry = (campaign.gmLibrary[type] || []).find(x => x.id === parts[5]); if (!entry) return error(res, 404, 'Not found'); const body = await readBody(req); const validationError = validateLibraryContent(type, body.data || entry.data); if (validationError) return error(res, 400, validationError); const before = clone(entry); if (typeof body.name === 'string') entry.name = body.name.slice(0, 120); if (body.data && typeof body.data === 'object') entry.data = clone(body.data); entry.updatedAt = now(); entry.archivedAt = null; audit(campaign, actor, 'library.update', type, entry.id, 'state', before, entry); save(); return json(res, 200, entry); }
    if (req.method === 'DELETE' && parts[3] === 'library' && parts[4] && parts[5]) { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const type = parts[4]; const entries = campaign.gmLibrary[type] || []; const index = entries.findIndex(x => x.id === parts[5]); if (index < 0) return error(res, 404, 'Not found'); const removed = entries[index]; if (removed.archivedAt) return error(res, 409, 'Content is already archived.'); removed.archivedAt = now(); audit(campaign, actor, 'library.archive', type, removed.id, null, removed, null); save(); return json(res, 200, { archived: true }); }
    if (req.method === 'POST' && parts[3] === 'player-access' && parts[4] === 'regenerate') { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const newToken = token(); campaign.playerTokenHash = hash(newToken); save(); audit(campaign, actor, 'access.regenerate', 'campaign', campaign.id, 'playerAccess', null, 'regenerated'); save(); return json(res, 200, { playerToken: newToken }); }
    if (req.method === 'POST' && parts[3] === 'participants' && parts[4] && parts[5] === 'revoke') { if (actor.role !== 'GM') return error(res, 403, 'GM access required'); const participant = db.participants[parts[4]]; if (!participant || participant.campaignId !== campaign.id) return error(res, 404, 'Not found'); participant.revoked = true; participant.revokedAt = now(); audit(campaign, actor, 'participant.revoke', 'participant', participant.id, 'revoked', false, true); save(); return json(res, 200, { ok: true }); }
    if (req.method === 'GET' && parts[3] === 'export') { if (actor.role !== 'GM') return error(res, 404, 'Not found'); const exported = JSON.parse(JSON.stringify(campaign)); delete exported.gmTokenHash; delete exported.playerTokenHash; return json(res, 200, { schemaVersion: 1, exportedAt: now(), campaign: exported, participants: Object.values(db.participants).filter(p => p.campaignId === campaign.id).map(p => ({ id: p.id, nickname: p.nickname, characterId: p.characterId, revoked: p.revoked })) }); }
    if (req.method === 'POST' && parts[3] === 'characters' && parts[4] && parts[5] === 'claim') {
      const character = campaign.characters[parts[4]]; if (!character) return error(res, 404, 'Not found'); if (actor.role !== 'GM' && character.ownerId && character.ownerId !== actor.id) return error(res, 409, 'This character is already assigned.'); if (actor.role === 'PLAYER' && character.ownerId === actor.id) return json(res, 200, publicCharacter(character, false)); const before = character.ownerId; character.ownerId = actor.role === 'GM' ? (await readBody(req)).participantId || null : actor.id; character.version += 1; if (actor.role === 'PLAYER') db.participants[actor.id].characterId = character.id; audit(campaign, actor, 'character.claim', 'character', character.id, 'ownerId', before, character.ownerId); save(); return json(res, 200, publicCharacter(character, true));
    }
    if (req.method === 'PATCH' && parts[3] === 'characters' && parts[4]) {
      const character = campaign.characters[parts[4]]; if (!character) return error(res, 404, 'Not found'); if (actor.role === 'PLAYER' && character.ownerId !== actor.id) return error(res, 404, 'Not found'); const body = await readBody(req); if (actor.role === 'PLAYER' && campaign.mode === 'PLAY' && Object.prototype.hasOwnProperty.call(body, 'companion')) { const incoming = body.companion || {}; const current = character.companion || {}; for (const key of ['name', 'evasion', 'stressMax', 'experiences']) if (JSON.stringify(incoming[key] ?? null) !== JSON.stringify(current[key] ?? null)) return error(res, 403, 'Companion configuration is locked during PLAY.'); } const allowed = actor.role === 'GM' || campaign.mode === 'PREPARATION' ? ['name','className','ancestry','community','subclassName','armorName','level','hp','hpMax','hope','stress','armor','complete','inventory','privateNotes','traits','experiences','domainCards','primaryWeapon','secondaryWeapon','evasion','armorScore','majorThreshold','severeThreshold','avatarUrl','beastformName','beastformStress','channelElement','companion','element','prayerDice','slayerDice'] : ['hp','hope','stress','inventory','domainCards','beastformStress','companion','prayerDice','slayerDice']; const requested = allowed.filter(key => Object.prototype.hasOwnProperty.call(body, key)); const stale = Number(body.version) !== character.version; const fieldVersions = character.lastFieldVersions; if (stale && (!fieldVersions || requested.some(key => Number(fieldVersions[key] || 0) > Number(body.version)))) return error(res, 409, 'Conflict: character changed elsewhere.'); const changes = {}; requested.forEach(key => { changes[key] = body[key]; }); Object.assign(changes, applyDerivedValues(character, changes)); const modelError = validateCharacterModel(character, changes); if (modelError) return error(res, 400, modelError); const validationError = validateCharacterChanges(character, changes); if (validationError) return error(res, 400, validationError); const before = {}; Object.keys(changes).forEach(k => before[k] = character[k]); Object.assign(character, changes); const nextVersion = character.version + 1; character.lastFieldVersions = { ...(character.lastFieldVersions || {}) }; Object.keys(changes).forEach(key => { character.lastFieldVersions[key] = nextVersion; }); character.version = nextVersion; audit(campaign, actor, 'character.update', 'character', character.id, 'state', before, changes); save(); return json(res, 200, publicCharacter(character, actor.role !== 'GM' && character.ownerId === actor.id));
    }
    if (req.method === 'POST' && parts[3] === 'undo' && parts[4]) {
      const target = db.events.find(e => e.id === parts[4] && e.campaignId === campaign.id); if (!target || target.entityType !== 'character' || target.operation !== 'character.update') return error(res, 404, 'Not found'); if (actor.role !== 'GM' && target.actorId !== actor.id) return error(res, 403, 'You can only undo your own actions.'); const character = campaign.characters[target.entityId]; const targetPrevious = target.undoPreviousValue || target.previousValue; const targetNew = target.undoNewValue || target.newValue; if (!character || !targetPrevious || !targetNew) return error(res, 409, 'This action cannot be undone.'); for (const [key, value] of Object.entries(targetNew)) if (JSON.stringify(character[key]) !== JSON.stringify(value)) return error(res, 409, 'Conflict: this character changed after the original action.'); const before = {}; for (const [key, value] of Object.entries(targetPrevious)) { before[key] = character[key]; character[key] = value; } character.version += 1; audit(campaign, actor, 'undo', 'character', character.id, 'state', before, targetPrevious); save(); return json(res, 200, publicCharacter(character, actor.role !== 'GM' && character.ownerId === actor.id));
    }
    return error(res, 404, 'Not found');
  } catch (e) { metrics.errors += 1; structuredLog('error', 'request_failed', { method: req.method, path: url.pathname, error: e.message }); return error(res, e.message === 'Invalid JSON' ? 400 : 500, e.message === 'Invalid JSON' ? e.message : 'Internal server error'); }
}

function serveStatic(req, res) {
  if (process.env.SERVE_STATIC !== '1' || req.method !== 'GET') return false;
  const requested = new URL(req.url, 'http://localhost').pathname;
  if (requested.startsWith('/avatars/')) { const filename = path.basename(requested); const target = path.join(avatarDir, filename); if (!fs.existsSync(target)) return false; const ext = path.extname(target).toLowerCase(); const type = ext === '.png' ? 'image/png' : ext === '.webp' ? 'image/webp' : 'image/jpeg'; res.writeHead(200, { 'content-type': type, 'cache-control': 'private, max-age=3600' }); res.end(fs.readFileSync(target)); return true; }
  const relative = requested === '/' ? 'index.html' : requested.replace(/^\/+/, '');
  const target = path.resolve(process.cwd(), 'dist', relative);
  const distRoot = path.resolve(process.cwd(), 'dist');
  const safeTarget = target.startsWith(distRoot) ? target : path.join(distRoot, 'index.html');
  const finalTarget = fs.existsSync(safeTarget) && fs.statSync(safeTarget).isFile() ? safeTarget : path.join(distRoot, 'index.html');
  if (!fs.existsSync(finalTarget)) return false;
  const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.svg': 'image/svg+xml' };
  res.writeHead(200, { 'content-type': types[path.extname(finalTarget)] || 'application/octet-stream', 'cache-control': relative === 'index.html' ? 'no-cache' : 'public, max-age=31536000, immutable' }); res.end(fs.readFileSync(finalTarget)); return true;
}
const server = http.createServer(async (req, res) => {
  metrics.requests += 1;
  const requestId = crypto.randomUUID(); res.setHeader('x-request-id', requestId); res.on('finish', () => { const status = String(res.statusCode); metrics.responses[status] = (metrics.responses[status] || 0) + 1; if (res.statusCode >= 500) metrics.errors += 1; });
  res.setHeader('access-control-allow-origin', process.env.CORS_ORIGIN || 'http://127.0.0.1:5173');
  res.setHeader('access-control-allow-credentials', 'true');
  res.setHeader('access-control-allow-headers', 'authorization,content-type');
  res.setHeader('access-control-allow-methods', 'GET,POST,PATCH,OPTIONS');
  res.setHeader('x-content-type-options', 'nosniff');
  res.setHeader('referrer-policy', 'no-referrer');
  if (req.method === 'OPTIONS') return res.end();
  const clientIp = process.env.TRUST_PROXY === '1' ? String(req.headers['x-forwarded-for'] || '').split(',')[0].trim() || req.socket.remoteAddress || 'unknown' : req.socket.remoteAddress || 'unknown'; const routeKey = String(req.url || '').split('?')[0]; const authRoute = routeKey === '/api/session' || routeKey === '/api/campaigns' || routeKey.endsWith('/join'); const limit = authRoute ? Number(process.env.RATE_LIMIT_AUTH_MAX || 20) : Number(process.env.RATE_LIMIT_MAX || 120); if (await rateLimited(`${clientIp}:${routeKey}`, limit)) { res.setHeader('retry-after', '60'); structuredLog('security', 'rate_limit_exceeded', { clientIp, route: routeKey, method: req.method }); return error(res, 429, 'Too many requests. Try again shortly.'); }
  const pathname = new URL(req.url, `http://${req.headers.host || 'localhost'}`).pathname;
  if (pathname === '/health' || pathname === '/metrics' || pathname.startsWith('/api/')) return route(req, res);
  if (serveStatic(req, res)) return;
  route(req, res);
});
async function boot() { if (process.env.NODE_ENV === 'production' && process.env.REQUIRE_PRODUCTION_SERVICES === '1' && (!postgres || !process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY)) throw new Error('Production requires DATABASE_URL and Supabase object-storage credentials.'); if (postgres) { await postgres.migrate(); db = await postgres.hydrate(db); db.sessions = db.sessions || {}; } const listenHost = process.env.HOST || '0.0.0.0'; server.listen(port, listenHost, () => console.log(`DaggerForge API listening on http://${listenHost}:${port}${postgres ? ' (normalized Postgres)' : ''}`)); if (process.env.ENABLE_BACKUPS === '1') { const interval = Math.max(60_000, Number(process.env.BACKUP_INTERVAL_MS || 21_600_000)); setInterval(() => { backupSnapshot().catch(error => { metrics.errors += 1; console.error(`Backup failed: ${error.message}`); }); }, interval); } }
boot().catch(error => { console.error(`Unable to start persistence layer: ${error.message}`); process.exitCode = 1; });
