const { expect, test } = require('@playwright/test');

test.describe('desktop campaign workflow', () => {
test.skip(({ isMobile }) => isMobile, 'Campaign creation is covered in the desktop flow; mobile coverage focuses on drawer and dialog behavior.');
test('GM can create a live campaign and open the character workflow', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: /server access/i }).first().click();
  await page.getByRole('heading', { name: /create a live campaign/i }).waitFor();
  await page.getByLabel('Campaign name').fill('Browser E2E Campaign');
  await page.getByRole('button', { name: /create campaign/i }).click();
  await expect(page.getByRole('heading', { name: /campaign overview/i })).toBeVisible({ timeout: 15000 });
  await page.getByRole('button', { name: 'Characters', exact: true }).click();
  await page.getByRole('button', { name: /add character/i }).first().click();
  await page.getByLabel('Character name').fill('Browser Hero');
  await page.getByRole('button', { name: 'Continue' }).click();
  const heritageDialog = page.getByRole('dialog', { name: 'Heritage and class' });
  await heritageDialog.getByLabel('Ancestry').selectOption({ label: 'Human' });
  await heritageDialog.getByLabel('Community').selectOption({ index: 1 });
  await heritageDialog.getByLabel('Class').selectOption({ label: 'Bard' });
  await heritageDialog.getByLabel('Archetype').selectOption({ index: 1 });
  await heritageDialog.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('dialog', { name: 'Equipment and Domains' }).getByLabel('Armor').selectOption({ index: 1 });
  await page.locator('.creation-choice-card').nth(0).click();
  await page.locator('.creation-choice-card').nth(1).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  const detailsDialog = page.getByRole('dialog', { name: 'Traits and Experiences' });
  await expect(detailsDialog).toBeVisible();
  await detailsDialog.getByLabel('Experience 1').fill('Trail guide');
  await detailsDialog.getByLabel('Experience 2').fill('Tactician');
  await page.getByRole('button', { name: 'Create character' }).click();
  await expect(page.getByRole('heading', { name: 'Browser Hero' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Traits', exact: true })).toBeVisible();
  await expect(page.locator('.sheet-trait-card')).toHaveCount(6);
  await expect(page.getByRole('heading', { name: 'Character configuration', exact: true })).toHaveCount(0);
  await expect(page.getByText('Evasion', { exact: true })).toBeVisible();
  await expect(page.getByText('Armor', { exact: true }).first()).toBeVisible();
  for (const trait of ['Agility', 'Strength', 'Finesse', 'Instinct', 'Presence', 'Knowledge']) await expect(page.getByText(trait, { exact: true })).toBeVisible();
  await expect(page.getByText('Trait Advancement uses: 0 / 3')).toBeVisible();
  await page.getByRole('button', { name: 'Level up' }).click();
  const advancementDialog = page.getByRole('dialog', { name: 'Level up to Level 2' });
  await expect(advancementDialog).toBeVisible();
  await advancementDialog.getByRole('button', { name: /Agility \+2.*Eligible/i }).click();
  await advancementDialog.getByRole('button', { name: /Presence 0.*Eligible/i }).click();
  await advancementDialog.getByRole('button', { name: 'Apply Advancement' }).click();
  await expect(page.getByText('Trait Advancement uses: 1 / 3')).toBeVisible({ timeout: 15000 });
  await expect(page.getByText('Increased this Tier: Agility, Presence')).toBeVisible();
  await expect(page.locator('.damage-thresholds')).toBeVisible();
  await expect(page.locator('.damage-thresholds')).toContainText('Severe');
  await page.reload();
  await page.getByRole('button', { name: 'Characters', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Browser Hero' })).toBeVisible();
  await expect(page.locator('.damage-thresholds')).toBeVisible();
  await page.getByRole('button', { name: 'Sessions', exact: true }).click();
  await page.getByRole('button', { name: /new session/i }).click();
  await expect(page.getByRole('dialog', { name: /edit session/i })).toBeVisible();
  await page.getByLabel('Title').fill('Browser Session');
  await expect(page.getByText('Saved', { exact: true })).toBeVisible({ timeout: 5000 });
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByRole('button', { name: 'Table View', exact: true }).click();
  await expect(page.getByText('Browser Session', { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: 'GM Library', exact: true }).click();
  await expect(page.getByLabel('Filter by source')).toBeVisible();
  await page.getByLabel('Filter by source').selectOption('daggerforge');
  await expect(page.getByText(/Daggerforge/i).first()).toBeVisible();
});
});

test('mobile navigation and Help are keyboard reachable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Open help' }).click();
  await expect(page.getByRole('dialog', { name: /daggerforge help/i })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog', { name: /daggerforge help/i })).toBeHidden();
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await expect(page.getByRole('navigation')).toBeVisible();
  await page.getByRole('button', { name: 'Overview' }).click();
  await expect(page.locator('.sidebar.open')).toHaveCount(0);
});

test('player join flow is scoped to player tools and can claim a character', async ({ page, request }) => {
  const createdResponse = await request.post('http://127.0.0.1:8787/api/campaigns', { data: { name: 'Player Browser Campaign' } });
  const created = await createdResponse.json();
  const characterResponse = await request.post('http://127.0.0.1:8787/api/campaigns/' + created.campaign.id + '/characters', {
    headers: { authorization: 'Bearer ' + created.gmToken },
    data: { name: 'Player Browser Hero', className: 'Bard', ancestry: 'Human' },
  });
  expect(characterResponse.ok()).toBeTruthy();
  await page.goto('/?campaign=' + encodeURIComponent(created.campaign.id) + '&token=' + encodeURIComponent(created.playerToken));
  await page.getByLabel('Nickname').fill('Browser Player');
  await page.getByRole('button', { name: 'Join campaign' }).click();
  await expect(page.getByRole('heading', { name: 'Player workspace' })).toBeVisible({ timeout: 15000 });
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Player workspace' })).toBeVisible({ timeout: 15000 });
  await expect(page.getByRole('button', { name: 'GM Library', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Participants', exact: true })).toHaveCount(0);
  if (page.viewportSize().width < 760) await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('button', { name: 'Characters', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Claim character' })).toBeVisible();
  await page.getByRole('button', { name: 'Claim character' }).click();
  await expect(page.getByText('Player Browser Hero')).toBeVisible();
});

test('GM can assign a participant and confirm access revocation', async ({ page, request }) => {
  await page.goto('/');
  if (page.viewportSize().width < 760) await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('button', { name: /server access/i }).first().click();
  await page.getByLabel('Campaign name').fill('Participant Browser Campaign');
  await page.getByRole('button', { name: /create campaign/i }).click();
  await page.waitForFunction(() => Boolean(localStorage.getItem('df-api-session')), undefined, { timeout: 15000 });
  await expect(page.getByRole('heading', { name: /campaign overview/i })).toBeVisible({ timeout: 15000 });
  const gm = await page.evaluate(() => JSON.parse(localStorage.getItem('df-api-session')));
  const playerAccessResponse = await request.post('http://127.0.0.1:8787/api/campaigns/' + gm.campaignId + '/player-access/regenerate', { headers: { authorization: 'Bearer ' + gm.token }, data: {} });
  const playerAccess = await playerAccessResponse.json();
  const characterResponse = await request.post('http://127.0.0.1:8787/api/campaigns/' + gm.campaignId + '/characters', { headers: { authorization: 'Bearer ' + gm.token }, data: { name: 'Assigned Browser Hero', className: 'Bard', ancestry: 'Human' } });
  const character = await characterResponse.json();
  const joinResponse = await request.post('http://127.0.0.1:8787/api/campaigns/' + gm.campaignId + '/join', { headers: { authorization: 'Bearer ' + playerAccess.playerToken }, data: { nickname: 'Browser Participant' } });
  expect(joinResponse.ok()).toBeTruthy();
  if (page.viewportSize().width < 760) await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('button', { name: 'Participants', exact: true }).click();
  const row = page.locator('.participant-row').filter({ hasText: 'Browser Participant' });
  await expect(row).toBeVisible();
  await row.getByRole('combobox').selectOption(character.id);
  await expect(row).toContainText('Assigned Browser Hero');
  await row.getByRole('button', { name: 'Revoke', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: /revoke browser participant/i });
  await expect(dialog).toBeVisible();
  await dialog.getByRole('button', { name: 'Keep access' }).click();
  await expect(dialog).toBeHidden();
  await row.getByRole('button', { name: 'Revoke', exact: true }).click();
  await page.getByRole('dialog', { name: /revoke browser participant/i }).getByRole('button', { name: 'Revoke access' }).click();
  await expect(row).toContainText('revoked');
});
