export type ApiSession = { campaignId: string; token: string; role: 'GM' | 'PLAYER'; participantId?: string };
const sessionKey = 'df-api-session';

export function apiBase() { if (import.meta.env.VITE_API_URL) return String(import.meta.env.VITE_API_URL).replace(/\/$/, ''); if (typeof window !== 'undefined' && window.location.port === '5173') return 'http://127.0.0.1:8787'; return ''; }
export function getApiSession(): ApiSession | null { try { const value = localStorage.getItem(sessionKey); return value ? JSON.parse(value) : null; } catch { return null; } }
export function setApiSession(session: ApiSession | null) { if (session) localStorage.setItem(sessionKey, JSON.stringify(session)); else localStorage.removeItem(sessionKey); }
export async function establishApiSession(campaignId: string, accessToken: string, recovery = false) { const response = await fetch(`${apiBase()}/api/session`, { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ campaignId, accessToken, recovery }) }); if (!response.ok) throw new Error('Unable to establish secure session.'); return response.json(); }
export async function endApiSession() { await fetch(`${apiBase()}/api/session/logout`, { method: 'POST', credentials: 'include' }).catch(() => {}); setApiSession(null); }
export async function apiRequest<T>(path: string, init: RequestInit = {}): Promise<T> { const session = getApiSession(); const method = String(init.method || 'GET').toUpperCase(); const mutation = !['GET', 'HEAD', 'OPTIONS'].includes(method); if (session && mutation && !path.endsWith('/presence') && (realtimeStatus === 'offline' || realtimeStatus === 'reconnecting')) throw new Error('This action is unavailable while the live connection is offline.'); const headers = new Headers(init.headers); headers.set('content-type', 'application/json'); if (session?.token) headers.set('authorization', `Bearer ${session.token}`); const response = await fetch(`${apiBase()}${path}`, { ...init, headers, credentials: 'include' }); if (!response.ok) throw new Error((await response.json().catch(() => null))?.error || `API request failed (${response.status})`); return response.json(); }

export type RealtimeEvent = { id?: string; type?: string; operation?: string; entityType?: string; entityId?: string; createdAt?: string; [key: string]: unknown };
export type RealtimeStatus = 'connecting' | 'connected' | 'reconnecting' | 'offline';
let realtimeStatus: RealtimeStatus = 'offline';
export function getRealtimeStatus() { return realtimeStatus; }
export function startCampaignRealtime(campaignId: string, handlers: { onStatus?: (status: RealtimeStatus) => void; onEvent: (event: RealtimeEvent) => void; onPresence?: (presence: unknown) => void }) {
  let source: EventSource | null = null; let stopped = false; let delay = 1000; let reconnectAttempts = 0; let heartbeat: number | undefined; const seen = new Set<string>(); const reportStatus = (status: RealtimeStatus) => { realtimeStatus = status; handlers.onStatus?.(status); };
  const recover = async () => { let offset = 0; for (let page = 0; page < 10 && !stopped; page += 1) { const data = await apiRequest<{ events: RealtimeEvent[]; nextOffset?: number | null }>(`/api/campaigns/${campaignId}/events?limit=100&offset=${offset}`); const events = data.events || []; events.slice().reverse().forEach(event => { if (!event.id || !seen.has(event.id)) { if (event.id) seen.add(event.id); handlers.onEvent(event); } }); if (data.nextOffset == null || !events.length) break; offset = data.nextOffset; } };
  const connect = async () => { if (stopped) return; reportStatus(reconnectAttempts ? 'reconnecting' : 'connecting'); try { await recover(); } catch { reportStatus('offline'); if (stopped) return; window.setTimeout(connect, delay); delay = Math.min(delay * 2, 30000); reconnectAttempts += 1; return; } if (stopped) return; source = new EventSource(`${apiBase()}/api/campaigns/${campaignId}/stream`, { withCredentials: true }); source.onopen = () => { delay = 1000; reconnectAttempts = 0; reportStatus('connected'); }; source.onmessage = event => { try { const value = JSON.parse(event.data) as RealtimeEvent; if (value.id && seen.has(value.id)) return; if (value.id) seen.add(value.id); if (value.type !== 'connected') handlers.onEvent(value); } catch { /* malformed events are ignored and recovered on reconnect */ } }; source.onerror = () => { source?.close(); source = null; if (!stopped) { reportStatus('reconnecting'); window.setTimeout(connect, delay); delay = Math.min(delay * 2, 30000); reconnectAttempts += 1; } }; };
  const heartbeatTick = () => apiRequest<{ presence: unknown }>(`/api/campaigns/${campaignId}/presence`, { method: 'POST', body: '{}' }).then(data => handlers.onPresence?.(data.presence)).catch(() => { if (!stopped) reportStatus('offline'); });
  const reconnect = () => { if (stopped) return; source?.close(); source = null; delay = 1000; reconnectAttempts = 0; void connect(); };
  window.addEventListener('df-reconnect', reconnect);
  heartbeat = window.setInterval(heartbeatTick, 20000); heartbeatTick(); connect();
  return () => { stopped = true; if (heartbeat) window.clearInterval(heartbeat); source?.close(); window.removeEventListener('df-reconnect', reconnect); reportStatus('offline'); };
}
