import React, { useEffect, useState } from 'react';
import { Archive, AlertTriangle, Trash2 } from 'lucide-react';
import { apiRequest, getApiSession, setApiSession } from './api';

export default function CampaignSettings({ PageTitle, onDeleted }: { PageTitle: React.ComponentType<any>; onDeleted: () => void }) {
  const session = getApiSession(); const [campaign, setCampaign] = useState<{id:string;name:string;mode:string;archivedAt?:string} | null>(null); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [confirmName, setConfirmName] = useState(''); const [confirmText, setConfirmText] = useState('');
  useEffect(() => { if (session) apiRequest<any>(`/api/campaigns/${session.campaignId}`).then(setCampaign).catch(e => setMessage(e instanceof Error ? e.message : 'Unable to load campaign settings.')); }, []);
  const archive = async () => { if (!session || !window.confirm('Archive this campaign? It will become read-only.')) return; setBusy(true); try { const result = await apiRequest<{archivedAt:string}>(`/api/campaigns/${session.campaignId}/archive`, { method: 'POST', body: '{}' }); setCampaign(x => x ? { ...x, archivedAt: result.archivedAt } : x); setMessage('Campaign archived. Existing exports remain available.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to archive campaign.'); } finally { setBusy(false); } };
  const remove = async () => { if (!session) return; if (!window.confirm('Permanently delete this campaign and its players, characters, events, and encounters?')) return; setBusy(true); try { await apiRequest(`/api/campaigns/${session.campaignId}`, { method: 'DELETE', body: JSON.stringify({ confirmName, confirmText }) }); setApiSession(null); onDeleted(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to delete campaign.'); } finally { setBusy(false); } };
  return <><PageTitle eyebrow="CAMPAIGN SETTINGS" title="Campaign settings" description="Control lifecycle, access, and destructive campaign actions." />{message && <div className="inline-feedback">{message}</div>}<section className="settings-grid"><div className="panel settings-card"><div className="settings-icon"><Archive size={19}/></div><div><h2>Archive campaign</h2><p>Archive freezes campaign mutations while preserving access to exports and historical data.</p><button className="button secondary" disabled={busy || Boolean(campaign?.archivedAt)} onClick={archive}>{campaign?.archivedAt ? 'Archived' : 'Archive campaign'}</button></div></div><div className="panel settings-card destructive"><div className="settings-icon"><AlertTriangle size={19}/></div><div><h2>Delete campaign permanently</h2><p>This cannot be undone. Type the exact campaign name and DELETE CAMPAIGN to confirm.</p><label className="form-label">Campaign name<input className="form-input" value={confirmName} onChange={e => setConfirmName(e.target.value)} placeholder={campaign?.name || 'Campaign name'}/></label><label className="form-label">Confirmation<input className="form-input" value={confirmText} onChange={e => setConfirmText(e.target.value)} placeholder="DELETE CAMPAIGN"/></label><button className="button danger-button" disabled={busy || confirmName !== campaign?.name || confirmText !== 'DELETE CAMPAIGN'} onClick={remove}><Trash2 size={15}/> Delete campaign</button></div></div></section></>;
}
