import React, { useState } from 'react';
import { Archive, Download, Upload } from 'lucide-react';
import { apiRequest, establishApiSession, setApiSession } from './api';

export default function CampaignDataTools({ PageTitle }: { PageTitle: React.ComponentType<any> }) {
  const [preview, setPreview] = useState<any>(null); const [fileName, setFileName] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [backupMessage, setBackupMessage] = useState('');
  const read = (file: File) => { setFileName(file.name); const reader = new FileReader(); reader.onload = () => { try { const value = JSON.parse(String(reader.result || '')); if (value.schemaVersion !== 1 || !value.campaign) throw new Error('This is not a DaggerForge schema v1 export.'); setPreview(value); setMessage('Validated export. Import always creates a new campaign.'); } catch (e) { setPreview(null); setMessage(e instanceof Error ? e.message : 'Unable to read export.'); } }; reader.readAsText(file); };
  const importCampaign = async () => { if (!preview) return; setBusy(true); try { const result = await apiRequest<{campaign:{id:string;name:string};gmToken:string;playerToken:string;importedCharacters:number;importedParticipants:Array<{nickname:string;participantToken:string;characterId:string|null}>}>('/api/campaigns/import', { method: 'POST', body: JSON.stringify(preview) }); const credentials = new Blob([JSON.stringify({ campaign: result.campaign, gmToken: result.gmToken, playerToken: result.playerToken, participants: result.importedParticipants }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(credentials); const link = document.createElement('a'); link.href = url; link.download = `${result.campaign.name}-access-credentials.json`; link.click(); URL.revokeObjectURL(url); await establishApiSession(result.campaign.id, result.gmToken); setApiSession({ campaignId: result.campaign.id, token: '', role: 'GM' }); setMessage(`Imported ${result.campaign.name} with ${result.importedCharacters} characters and ${result.importedParticipants?.length || 0} player identities. Credentials downloaded; reloading…`); window.setTimeout(() => window.location.reload(), 500); } catch (e) { setMessage(e instanceof Error ? e.message : 'Import failed.'); } finally { setBusy(false); } };
  const exportCampaign = async () => { try { const session = JSON.parse(localStorage.getItem('df-api-session') || 'null'); if (!session) throw new Error('Connect a campaign before exporting.'); const data = await apiRequest<any>(`/api/campaigns/${session.campaignId}/export`); const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${data.campaign?.name || 'daggerforge-campaign'}.json`; link.click(); URL.revokeObjectURL(url); setMessage('Campaign export downloaded.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Export failed.'); } };
  const backup = async () => { try { const session = JSON.parse(localStorage.getItem('df-api-session') || 'null'); if (!session) throw new Error('Connect a campaign before creating a backup.'); const result = await apiRequest<{campaigns:number;createdAt:string}>(`/api/campaigns/${session.campaignId}/backup`, { method: 'POST', body: '{}' }); setBackupMessage(`Backup created at ${new Date(result.createdAt).toLocaleString()} (${result.campaigns} campaigns).`); } catch (e) { setBackupMessage(e instanceof Error ? e.message : 'Backup failed.'); } };
  return <><PageTitle eyebrow="CAMPAIGN DATA" title="Import, export & recovery" description="Move campaigns safely between environments and create an operator backup on demand." />{message && <div className="inline-feedback">{message}</div>}<div className="data-tools-grid"><section className="panel settings-card"><div className="settings-icon"><Upload size={19}/></div><div><h2>Import campaign</h2><p>Choose a schema v1 JSON export. The preview is validated before a new campaign is created.</p><label className="button secondary"><Upload size={15}/> Choose export<input hidden type="file" accept="application/json,.json" onChange={e => e.target.files?.[0] && read(e.target.files[0])}/></label>{fileName && <p className="file-name">{fileName}</p>}{preview && <div className="import-preview"><b>{preview.campaign.name}</b><span>{Object.keys(preview.campaign.characters || {}).length} characters · {preview.campaign.gmLibrary ? 'GM library included' : 'No GM library'}</span><button className="button primary" disabled={busy} onClick={importCampaign}>{busy ? 'Importing…' : 'Create imported campaign'}</button></div>}</div></section><section className="panel settings-card"><div className="settings-icon"><Download size={19}/></div><div><h2>Export current campaign</h2><p>Download a portable JSON export without access-token hashes. Use it for migration or disaster recovery.</p><button className="button secondary" onClick={exportCampaign}><Archive size={15}/> Download export</button></div></section><section className="panel settings-card"><div className="settings-icon"><Archive size={19}/></div><div><h2>Operator backup</h2><p>Create a server-side rotating backup snapshot. Automatic backups are enabled with ENABLE_BACKUPS=1.</p><button className="button secondary" onClick={backup}>Create backup now</button>{backupMessage && <p className="file-name">{backupMessage}</p>}</div></section></div></>;
}
