import React, { useEffect, useState } from 'react';
import { Archive, AlertTriangle, Trash2 } from 'lucide-react';
import { apiRequest, getApiSession, setApiSession } from './api';
import { Modal } from './ProductionOverlays';

export default function CampaignSettings({ PageTitle, onDeleted }: { PageTitle: React.ComponentType<any>; onDeleted: () => void }) {
  const session = getApiSession(); const [campaign, setCampaign] = useState<{ id: string; name: string; mode: string; archivedAt?: string } | null>(null); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [confirmName, setConfirmName] = useState(''); const [confirmText, setConfirmText] = useState(''); const [action, setAction] = useState<'archive' | 'delete' | null>(null);
  useEffect(() => { if (session) apiRequest<any>(`/api/campaigns/${session.campaignId}`).then(setCampaign).catch(event => setMessage(event instanceof Error ? event.message : 'Unable to load campaign settings.')); }, []);
  const archive = async () => { if (!session) return; setBusy(true); try { const result = await apiRequest<{ archivedAt: string }>(`/api/campaigns/${session.campaignId}/archive`, { method: 'POST', body: '{}' }); setCampaign(current => current ? { ...current, archivedAt: result.archivedAt } : current); setMessage('Campaign archived. Existing exports remain available.'); setAction(null); } catch (event) { setMessage(event instanceof Error ? event.message : 'Unable to archive campaign.'); } finally { setBusy(false); } };
  const remove = async () => { if (!session) return; setBusy(true); try { await apiRequest(`/api/campaigns/${session.campaignId}`, { method: 'DELETE', body: JSON.stringify({ confirmName, confirmText }) }); setApiSession(null); onDeleted(); } catch (event) { setMessage(event instanceof Error ? event.message : 'Unable to delete campaign.'); } finally { setBusy(false); } };
  return <><PageTitle eyebrow="CAMPAIGN SETTINGS" title="Campaign settings" description="Control lifecycle, access, and destructive campaign actions." />{message && <div className="inline-feedback" role="status">{message}</div>}<section className="settings-grid"><div className="panel settings-card"><div className="settings-icon"><Archive size={19} /></div><div><h2>Archive campaign</h2><p>Archive freezes campaign mutations while preserving access to exports and historical data.</p><button className="button secondary" disabled={busy || Boolean(campaign?.archivedAt)} onClick={() => setAction('archive')}>{campaign?.archivedAt ? 'Archived' : 'Archive campaign'}</button></div></div><div className="panel settings-card destructive"><div className="settings-icon"><AlertTriangle size={19} /></div><div><h2>Delete campaign permanently</h2><p>This cannot be undone. Type the exact campaign name and DELETE CAMPAIGN to confirm.</p><label className="form-label">Campaign name<input className="form-input" value={confirmName} onChange={event => setConfirmName(event.target.value)} placeholder={campaign?.name || 'Campaign name'} /></label><label className="form-label">Confirmation<input className="form-input" value={confirmText} onChange={event => setConfirmText(event.target.value)} placeholder="DELETE CAMPAIGN" /></label><button className="button danger-button" disabled={busy || confirmName !== campaign?.name || confirmText !== 'DELETE CAMPAIGN'} onClick={() => setAction('delete')}><Trash2 size={15} /> Delete campaign</button></div></div></section>{action === 'archive' && <Modal title="Archive this campaign?" eyebrow="CAMPAIGN LIFECYCLE" onClose={() => setAction(null)}><p>Archiving makes the campaign read-only and preserves exports and history. You can still review it after this action.</p><div className="modal-actions"><button className="button secondary" onClick={() => setAction(null)} disabled={busy}>Cancel</button><button className="button primary" onClick={archive} disabled={busy}>{busy ? 'Archiving…' : 'Archive campaign'}</button></div></Modal>}{action === 'delete' && <Modal title="Delete this campaign permanently?" eyebrow="DESTRUCTIVE ACTION" onClose={() => setAction(null)}><p>All participants, characters, encounters, and history will be removed. This cannot be undone.</p><div className="modal-actions"><button className="button secondary" onClick={() => setAction(null)} disabled={busy}>Cancel</button><button className="button danger-button" onClick={remove} disabled={busy}>{busy ? 'Deleting…' : 'Delete permanently'}</button></div></Modal>}</>;
}
