import React, { useMemo, useState } from 'react';
import { ArrowLeft, Check, Plus, X } from 'lucide-react';
import classes from './content/daggerforge/srd/classes.json';
import ancestries from './content/daggerforge/srd/ancestries.json';
import communities from './content/daggerforge/srd/communities.json';
import domains from './content/daggerforge/srd/domains.json';
import equipment from './content/daggerforge/srd/equipment.json';

type Draft = Record<string, any>;
type Props = { onClose: () => void; onCreate: (draft: Draft) => Promise<void> };
const traits = ['agility', 'strength', 'finesse', 'instinct', 'presence', 'knowledge'];
const armor = ((equipment as any).armor || []) as any[];
const weapons = ((equipment as any).weapons || []) as any[];

export default function CharacterWizard({ onClose, onCreate }: Props) {
  const [step, setStep] = useState(1);
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const [draft, setDraft] = useState<Draft>({ name: '', className: '', subclassName: '', ancestry: '', community: (communities as any[])[0]?.name || '', level: 1, hpMax: 6, armorName: armor[0]?.name || '', primaryWeapon: '', secondaryWeapon: '', traits: Object.fromEntries(traits.map(name => [name, { value: '0', marked: false }])), experiences: [], domainCardNames: [], inventory: [] });
  const selectedClass = (classes as any[]).find(item => item.name === draft.className);
  const subclasses = Object.values(selectedClass?.subclasses || {}) as any[];
  const availableCards = (domains as any[]).slice(0, 80);
  const set = (key: string, value: any) => setDraft((current: Draft) => ({ ...current, [key]: value }));
  const validate = () => {
    if (!draft.name.trim()) return 'Enter a character name.';
    if (!draft.ancestry || !draft.community || !draft.className || !draft.subclassName) return 'Choose an ancestry, community, class, and subclass.';
    if (!draft.armorName) return 'Choose starting armor.';
    if (traits.some(name => !/^-?\d+$/.test(String(draft.traits?.[name]?.value ?? '')) || Number(draft.traits[name].value) < -3 || Number(draft.traits[name].value) > 3)) return 'Each trait must be a whole number from -3 to 3.';
    if ((draft.experiences || []).some((item: any) => !item.text.trim() || !/^[+-]?\d+$/.test(item.modifier))) return 'Complete each experience or remove the empty row.';
    if ((draft.domainCardNames || []).some((name: string) => !availableCards.some(card => card.name === name))) return 'Choose domain cards from the available card list.';
    return '';
  };
  const next = () => { const message = step === 1 && !draft.name.trim() ? 'Enter a character name.' : step === 2 && (!draft.ancestry || !draft.community || !draft.className || !draft.subclassName) ? 'Complete the heritage and class choices.' : step === 3 && !draft.armorName ? 'Choose starting armor.' : ''; if (message) { setError(message); return; } setError(''); setStep(value => Math.min(5, value + 1)); };
  const finish = async () => { const message = validate(); if (message) { setError(message); return; } setSaving(true); setError(''); try { await onCreate({ ...draft, complete: true, hp: Number(draft.hpMax), traits: draft.traits, experiences: draft.experiences.filter((item: any) => item.text.trim()), inventory: (draft.inventory || []).filter((item: string) => item.trim()), domainCardNames: draft.domainCardNames, primaryWeapon: draft.primaryWeapon || undefined, secondaryWeapon: draft.secondaryWeapon || undefined }); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to create character.'); } finally { setSaving(false); } };
  const addExperience = () => set('experiences', [...(draft.experiences || []), { text: '', modifier: '+2' }]);
  const addItem = () => set('inventory', [...(draft.inventory || []), '']);
  const title = ['Identity', 'Heritage and class', 'Starting loadout', 'Traits and experiences', 'Review and complete'][step - 1];
  return <div className="modal-backdrop" onClick={onClose}><div className="modal wizard-modal complete-character-wizard" onClick={event => event.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="Close character creation"><X size={18} /></button><div className="wizard-progress"><span>CHARACTER CREATION</span><b>STEP {step} OF 5</b><i style={{ width: `${step * 20}%` }} /></div><h2>{title}</h2><p>Use the authoritative Daggerheart options. You can keep editing this sheet during Preparation.</p>
    {step === 1 && <div className="wizard-step-grid"><label className="form-label">Character name<input autoFocus className="form-input" value={draft.name} onChange={event => set('name', event.target.value)} placeholder="Alder Vane" /></label><label className="form-label">Level<input className="form-input" type="number" min="1" max="10" value={draft.level} onChange={event => set('level', Number(event.target.value))} /></label><label className="form-label">Starting HP maximum<input className="form-input" type="number" min="1" max="24" value={draft.hpMax} onChange={event => set('hpMax', Number(event.target.value))} /></label></div>}
    {step === 2 && <div className="wizard-step-grid"><label className="form-label">Ancestry<select className="form-input" value={draft.ancestry} onChange={event => set('ancestry', event.target.value)}><option value="">Choose ancestry</option>{(ancestries as any[]).map(item => <option key={item.name} value={item.name}>{item.name}</option>)}</select></label><label className="form-label">Community<select className="form-input" value={draft.community} onChange={event => set('community', event.target.value)}><option value="">Choose community</option>{(communities as any[]).map(item => <option key={item.name} value={item.name}>{item.name}</option>)}</select></label><label className="form-label">Class<select className="form-input" value={draft.className} onChange={event => { const selected = (classes as any[]).find(item => item.name === event.target.value); setDraft(current => ({ ...current, className: event.target.value, subclassName: (Object.values(selected?.subclasses || {}) as any[])[0]?.name || '', hpMax: selected?.stats?.hp || current.hpMax })); }}><option value="">Choose class</option>{(classes as any[]).map(item => <option key={item.name} value={item.name}>{item.name}</option>)}</select></label><label className="form-label"><span>Subclass</span><select aria-label="Archetype" className="form-input" disabled={!draft.className} value={draft.subclassName} onChange={event => set('subclassName', event.target.value)}><option value="">Choose subclass</option>{subclasses.map(item => <option key={item.name} value={item.name}>{item.name}</option>)}</select></label></div>}
    {step === 3 && <><div className="wizard-step-grid"><label className="form-label">Armor<select className="form-input" value={draft.armorName} onChange={event => set('armorName', event.target.value)}><option value="">Choose armor</option>{armor.map(item => <option key={item.name} value={item.name}>{item.name} · score {item.score}</option>)}</select></label><label className="form-label">Primary weapon<select className="form-input" value={draft.primaryWeapon} onChange={event => set('primaryWeapon', event.target.value)}><option value="">No primary weapon</option>{weapons.filter(item => item.category === 'Primary').map(item => <option key={item.id} value={item.name}>{item.name} · {item.trait} · {item.damage}</option>)}</select></label><label className="form-label">Secondary weapon<select className="form-input" value={draft.secondaryWeapon} onChange={event => set('secondaryWeapon', event.target.value)}><option value="">No secondary weapon</option>{weapons.map(item => <option key={item.id} value={item.name}>{item.name} · {item.trait} · {item.damage}</option>)}</select></label></div><div className="detail-section wizard-loadout"><div className="card-title"><span className="section-label">DOMAIN CARDS</span><small>{draft.domainCardNames.length} selected</small></div><div className="wizard-card-list">{draft.domainCardNames.map((name: string, index: number) => <div className="repeatable-row" key={name + index}><select className="form-input" value={name} onChange={event => set('domainCardNames', draft.domainCardNames.map((card: string, cardIndex: number) => cardIndex === index ? event.target.value : card))}><option value="">Choose a card</option>{availableCards.map(card => <option key={card.name} value={card.name}>{card.name} · {card.domain} · Level {card.level}</option>)}</select><button className="icon-button" onClick={() => set('domainCardNames', draft.domainCardNames.filter((_: string, cardIndex: number) => cardIndex !== index))} aria-label="Remove domain card">×</button></div>)}</div><button className="text-button" onClick={() => set('domainCardNames', [...draft.domainCardNames, ''])}><Plus size={14} /> Add domain card</button></div></>}
    {step === 4 && <div className="wizard-detail-fields"><div className="detail-section"><div className="card-title"><span className="section-label">TRAITS</span><small>Whole numbers from -3 to 3</small></div><div className="config-grid trait-editor-grid">{traits.map(name => <label className="form-label" key={name}>{name[0].toUpperCase() + name.slice(1)}<input className="form-input" type="number" min="-3" max="3" value={draft.traits[name].value} onChange={event => setDraft((current: Draft) => ({ ...current, traits: { ...current.traits, [name]: { ...current.traits[name], value: event.target.value } } }))} /></label>)}</div></div><div className="detail-section"><div className="card-title"><span className="section-label">EXPERIENCES</span><button className="text-button" disabled={draft.experiences.length >= 2} onClick={addExperience}><Plus size={14} /> Add experience</button></div>{draft.experiences.map((item: any, index: number) => <div className="repeatable-row" key={index}><input className="form-input" aria-label={`Experience ${index + 1}`} value={item.text} placeholder="Experience" onChange={event => set('experiences', draft.experiences.map((row: any, rowIndex: number) => rowIndex === index ? { ...row, text: event.target.value } : row))} /><input className="form-input compact-number" aria-label={`Experience ${index + 1} modifier`} value={item.modifier} placeholder="+2" onChange={event => set('experiences', draft.experiences.map((row: any, rowIndex: number) => rowIndex === index ? { ...row, modifier: event.target.value } : row))} /><button className="icon-button" onClick={() => set('experiences', draft.experiences.filter((_: any, rowIndex: number) => rowIndex !== index))} aria-label="Remove experience">×</button></div>)}</div><div className="detail-section"><div className="card-title"><span className="section-label">INVENTORY</span><button className="text-button" onClick={addItem}><Plus size={14} /> Add item</button></div>{draft.inventory.map((item: string, index: number) => <div className="repeatable-row" key={index}><input className="form-input" aria-label={`Inventory item ${index + 1}`} value={item} placeholder="Item" onChange={event => set('inventory', draft.inventory.map((row: string, rowIndex: number) => rowIndex === index ? event.target.value : row))} /><button className="icon-button" onClick={() => set('inventory', draft.inventory.filter((_: string, rowIndex: number) => rowIndex !== index))} aria-label="Remove inventory item">×</button></div>)}</div></div>}
    {step === 5 && <div className="wizard-review"><div><span>Name</span><b>{draft.name}</b></div><div><span>Heritage</span><b>{draft.ancestry} · {draft.community}</b></div><div><span>Class</span><b>{draft.className} · {draft.subclassName}</b></div><div><span>Loadout</span><b>{draft.armorName || 'No armor'} · {draft.primaryWeapon || 'No primary weapon'}</b></div><div><span>Preparation status</span><b><Check size={15} /> Complete on creation</b></div></div>}
    {error && <div className="form-error" role="alert">{error}</div>}<div className="wizard-actions">{step > 1 && <button className="button secondary" onClick={() => { setError(''); setStep(value => value - 1); }}><ArrowLeft size={15} /> Back</button>}{step === 4 && <button className="button secondary" disabled={saving} onClick={finish}>Create character</button>}{step < 5 ? <button className="button primary" onClick={next}>Continue</button> : <button className="button primary" disabled={saving} onClick={finish}>{saving ? 'Creating…' : 'Create complete character'}</button>}</div>
  </div></div>;
}




