export const developmentCharacters = [
  { id: 'seed-c1', name: 'Alder Vane', className: 'Ranger', ancestry: 'Human', color: '#d4876a', initials: 'AV', hp: 8, hpMax: 12, hope: 3, stress: 1, armor: 2, armorScore: 2, evasion: 12, majorThreshold: 7, severeThreshold: 12, level: 3, complete: true, owner: 'seed-p1', ownerLabel: 'Mara · 8D4', inventory: ['Longbow', 'Hunter’s Cloak', 'Premium Bedroll'], notes: 'Watch the eastern ridge.', privateNotes: 'Watch the eastern ridge.', traits: { agility: { value: '+2' }, strength: { value: '+1' }, finesse: { value: '+2' }, instinct: { value: '+1' }, presence: { value: '+0' }, knowledge: { value: '+3' } }, experiences: [{ text: 'Wayfinder', modifier: '+2' }, { text: 'Read the stars', modifier: '+2' }], domainCards: [{ name: 'Vicious Entangle', inVault: false }], primaryWeapon: { sourceId: 'longbow', name: 'Longbow', traitRange: 'Agility · Far', damageDice: 'd8 phy', burden: 'Two-Handed', feature: 'Reliable', slot: 'Primary' } },
  { id: 'seed-c2', name: 'Nyx Emberfall', className: 'Wizard', ancestry: 'Infernis', color: '#7aa7d9', initials: 'NE', hp: 5, hpMax: 10, hope: 2, stress: 3, armor: 1, armorScore: 1, evasion: 10, majorThreshold: 6, severeThreshold: 10, level: 3, complete: true, owner: 'seed-p2', ownerLabel: 'Jailson · A7F', inventory: ['Arcane Focus', 'Piper Whistle'], notes: 'The dream keeps returning.', privateNotes: 'The dream keeps returning.', traits: { agility: { value: '+0' }, strength: { value: '-1' }, finesse: { value: '+1' }, instinct: { value: '+0' }, presence: { value: '+2' }, knowledge: { value: '+1' } }, experiences: [{ text: 'Occult Scholar', modifier: '+2' }], domainCards: [{ name: 'Book of Sitil', inVault: false }], primaryWeapon: { sourceId: 'arcane-staff', name: 'Arcane Staff', traitRange: 'Knowledge · Far', damageDice: 'd6 mag', burden: 'Two-Handed', feature: 'Spellcast', slot: 'Primary' } },
  { id: 'seed-c3', name: 'Bramble', className: 'Guardian', ancestry: 'Faerie', color: '#a98ad4', initials: 'BR', hp: 11, hpMax: 14, hope: 5, stress: 0, armor: 3, armorScore: 3, evasion: 9, majorThreshold: 8, severeThreshold: 14, level: 2, complete: false, inventory: ['Tower Shield'], notes: '', privateNotes: '', traits: { agility: { value: '+1' }, strength: { value: '+2' }, finesse: { value: '+0' }, instinct: { value: '+1' }, presence: { value: '+1' }, knowledge: { value: '+0' } }, experiences: [], domainCards: [] },
  { id: 'seed-c4', name: 'Seraphine Vale', className: 'Bard', ancestry: 'Elf', color: '#7bb78a', initials: 'SV', hp: 7, hpMax: 10, hope: 4, stress: 2, armor: 1, armorScore: 1, evasion: 10, majorThreshold: 6, severeThreshold: 10, level: 2, complete: true, owner: 'seed-p3', ownerLabel: 'Theo · C19', inventory: ['Lute', 'Speaking Orbs'], notes: '', privateNotes: '', traits: { agility: { value: '+0' }, strength: { value: '-1' }, finesse: { value: '+1' }, instinct: { value: '+0' }, presence: { value: '+2' }, knowledge: { value: '+1' } }, experiences: [{ text: 'Silver Tongue', modifier: '+2' }], domainCards: [], primaryWeapon: { sourceId: 'rapier', name: 'Rapier', traitRange: 'Finesse · Melee', damageDice: 'd8 phy', burden: 'One-Handed', feature: 'Quick', slot: 'Primary' } }
];

export const developmentLogs = [
  { id: 'seed-l1', actor: 'GM', text: 'started the session “Ashes at Dawn”', time: '2 min ago', accent: '#d0a75b', kind: 'session' },
  { id: 'seed-l2', actor: 'Mara · 8D4', text: 'marked 1 Stress on Alder Vane', time: '6 min ago', accent: '#d4876a', kind: 'character' },
  { id: 'seed-l3', actor: 'GM', text: 'added “Rotted Zombie” to the encounter', time: '9 min ago', accent: '#8b7ac1', kind: 'adversary' },
  { id: 'seed-l4', actor: 'Jailson · A7F', text: 'spent 1 Hope', time: '12 min ago', accent: '#7aa7d9', kind: 'character' }
];
