import React, { useState } from 'react';
import { Check } from 'lucide-react';
import { Modal } from './ProductionOverlays';

const traitNames = ['agility', 'strength', 'finesse', 'instinct', 'presence', 'knowledge'] as const;
const traitLabels: Record<typeof traitNames[number], string> = { agility: 'Agility', strength: 'Strength', finesse: 'Finesse', instinct: 'Instinct', presence: 'Presence', knowledge: 'Knowledge' };
type Character = { id: string; name: string; level: number; proficiency?: number; traits?: Record<string, { value?: string }>; traitProgression?: { tier?: number; increasedTraits?: string[]; traitAdvancementUses?: number } };
type Choice = { type: 'traits'; traits: string[] } | { type: 'proficiency' };
type Props = { c: Character; onClose: () => void; onSubmit: (payload: { level: number; choices: Choice[] }) => Promise<void> };

function tierForLevel(level: number) { return level >= 8 ? 4 : level >= 5 ? 3 : level >= 2 ? 2 : 1; }
function modifier(value: unknown) { const number = Number(value); return Number.isFinite(number) ? number > 0 ? `+${number}` : String(number) : '—'; }

export default function LevelUpDialog({ c, onClose, onSubmit }: Props) {
  const targetLevel = c.level + 1; const targetTier = tierForLevel(targetLevel); const currentTier = Number(c.traitProgression?.tier || tierForLevel(c.level)); const enteringNewTier = targetTier !== currentTier; const increased = enteringNewTier ? [] : (c.traitProgression?.increasedTraits || []); const uses = enteringNewTier ? 0 : Number(c.traitProgression?.traitAdvancementUses || 0);
  const [selectedChoices, setSelectedChoices] = useState<Array<'traits' | 'proficiency'>>(['traits', 'proficiency']); const [selectedTraits, setSelectedTraits] = useState<string[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const toggleChoice = (choice: 'traits' | 'proficiency') => setSelectedChoices(current => current.includes(choice) ? current.filter(item => item !== choice) : current.length < 2 ? [...current, choice] : current);
  const eligible = traitNames.filter(name => !increased.includes(name) && Number(c.traits?.[name]?.value) < 5);
  const submit = async () => { if (selectedChoices.length !== 2) return setError('Choose exactly two Advancement options.'); if (selectedChoices.includes('traits') && selectedTraits.length !== 2) return setError('Choose exactly two different eligible Traits.'); setBusy(true); setError(''); try { await onSubmit({ level: targetLevel, choices: selectedChoices.map(type => type === 'traits' ? { type, traits: selectedTraits } : { type }) }); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to apply Advancement.'); } finally { setBusy(false); } };
  return <Modal title={`Level up to Level ${targetLevel}`} eyebrow="ADVANCEMENT" onClose={() => { if (!busy) onClose(); }}><p>Choose exactly two Advancement options. Trait increases are permanent and current-Tier locks reset only when a new Tier begins.</p>{targetTier !== currentTier && <div className="security-note">Entering Tier {targetTier} clears the previous Tier’s Trait locks and uses without changing Trait values.</div>}<div className="advancement-choice-list"><button type="button" className={`advancement-choice${selectedChoices.includes('traits') ? ' selected' : ''}`} aria-pressed={selectedChoices.includes('traits')} disabled={(!selectedChoices.includes('traits') && selectedChoices.length >= 2) || eligible.length < 2 || uses >= 3} onClick={() => toggleChoice('traits')}><span><b>Increase two Traits by +1</b><small>{uses} / 3 uses this Tier · max +5</small></span>{selectedChoices.includes('traits') && <Check size={16} />}</button><button type="button" className={`advancement-choice${selectedChoices.includes('proficiency') ? ' selected' : ''}`} aria-pressed={selectedChoices.includes('proficiency')} disabled={!selectedChoices.includes('proficiency') && selectedChoices.length >= 2} onClick={() => toggleChoice('proficiency')}><span><b>Increase Proficiency by +1</b><small>Updates the character’s damage proficiency.</small></span>{selectedChoices.includes('proficiency') && <Check size={16} />}</button></div>{selectedChoices.includes('traits') && <div className="advancement-traits"><div className="card-title"><div><span className="section-label">TRAIT ADVANCEMENT</span><h3>Choose two unmarked Traits</h3></div><span>{selectedTraits.length} / 2 selected</span></div>{traitNames.map(name => { const value = modifier(c.traits?.[name]?.value); const locked = increased.includes(name); const capped = Number(c.traits?.[name]?.value) >= 5; const selected = selectedTraits.includes(name); return <button type="button" key={name} className={`advancement-trait${selected ? ' selected' : ''}`} disabled={locked || capped || (!selected && selectedTraits.length >= 2)} onClick={() => setSelectedTraits(current => current.includes(name) ? current.filter(item => item !== name) : [...current, name])}><span><b>{traitLabels[name]}</b><small>{value}{locked ? ' · Already increased this Tier' : capped ? ' · Maximum reached' : ' · Eligible'}</small></span>{selected && <Check size={16} />}</button>; })}</div>}{error && <div className="form-error" role="alert">{error}</div>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancel</button><button type="button" className="button primary" disabled={busy} onClick={submit}>{busy ? 'Applying…' : 'Apply Advancement'}</button></div></Modal>;
}
