import React, { useEffect, useRef, useState } from 'react';
import { Plus } from 'lucide-react';
import { apiRequest, getApiSession } from './api';
import { Modal } from './ProductionOverlays';

type Session = { id: string; title: string; notes: string; status: string; startedAt: string; endedAt: string | null };
export default function SessionsPanel({ PageTitle }: { PageTitle: React.ComponentType<any> }) {
  const [sessions, setSessions] = useState<Session[]>([]); const [busy, setBusy] = useState(true); const [message, setMessage] = useState(''); const [editing, setEditing] = useState<Session | null>(null); const [ending, setEnding] = useState<Session | null>(null); const [draft, setDraft] = useState({ title: '', notes: '' }); const [saveState, setSaveState] = useState('Saved'); const initialized = useRef(false); const session = getApiSession();
  const load = async () => { if (!session) { setBusy(false); return; } try { const data = await apiRequest<{ sessions: Session[] }>(`/api/campaigns/${session.campaignId}`); setSessions(data.sessions || []); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load sessions.'); } finally { setBusy(false); } };
  useEffect(() => { void load(); const sync = (event: Event) => { if ((event as CustomEvent).detail?.entityType === 'session') void load(); }; window.addEventListener('df-realtime-event', sync); return () => window.removeEventListener('df-realtime-event', sync); }, []);
  useEffect(() => { if (!editing || !initialized.current || !draft.title.trim() || !session) return; setSaveState('Saving…'); const timer = window.setTimeout(async () => { try { const updated = await apiRequest<Session>(`/api/campaigns/${session.campaignId}/sessions/${editing.id}`, { method: 'PATCH', body: JSON.stringify({ title: draft.title.trim(), notes: draft.notes }) }); setSessions(current => current.map(item => item.id === updated.id ? updated : item)); setEditing(current => current ? { ...current, ...updated } : current); setSaveState('Saved'); } catch (error) { setSaveState('Could not save'); setMessage(error instanceof Error ? error.message : 'Unable to save session.'); } }, 650); return () => window.clearTimeout(timer); }, [draft.title, draft.notes, editing?.id]);
  const start = async () => { if (!session) return setMessage('Connect a server campaign before starting a session.'); try { const created = await apiRequest<Session>(`/api/campaigns/${session.campaignId}/sessions`, { method: 'POST', body: JSON.stringify({ title: 'New Session', notes: '' }) }); setSessions(current => [created, ...current]); openEditor(created); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to start session.'); } };
  const openEditor = (item: Session) => { initialized.current = false; setEditing(item); setDraft({ title: item.title, notes: item.notes || '' }); window.setTimeout(() => { initialized.current = true; }, 0); };
  const end = async () => { if (!session || !ending) return; try { const updated = await apiRequest<Session>(`/api/campaigns/${session.campaignId}/sessions/${ending.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'ENDED' }) }); setSessions(current => current.map(item => item.id === updated.id ? updated : item)); setEnding(null); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to end session.'); } };
  const active = sessions.filter(item => item.status === 'ACTIVE'); const history = sessions.filter(item => item.status !== 'ACTIVE'); const row = (item: Session) => <div className={'session-row ' + (item.status === 'ACTIVE' ? 'active' : '')} key={item.id}><div className="session-date"><b>{new Date(item.startedAt).getDate()}</b><span>{new Date(item.startedAt).toLocaleString('en', { month: 'short' }).toUpperCase()}</span></div><div><span className={item.status === 'ACTIVE' ? 'live-tag' : 'muted-tag'}>{item.status === 'ACTIVE' ? 'LIVE NOW' : 'HISTORY'}</span><h2>{item.title}</h2><p>{item.notes || 'No session notes yet.'}</p></div><span className="session-duration">{item.status}</span><button className="text-button" onClick={() => openEditor(item)}>Edit</button>{item.status === 'ACTIVE' && <><button className="text-button" onClick={() => setEnding(item)}>End</button><button className="text-button" onClick={() => { window.dispatchEvent(new CustomEvent('df-filter-session', { detail: item.id })); window.dispatchEvent(new Event('df-open-history')); }}>View events</button></>}</div>;
  return <><PageTitle eyebrow="SESSIONS" title="Session history" description="Manage active table sessions and review the campaign timeline." action={<button className="button primary" onClick={start}><Plus size={16} /> New session</button>} />{message && <div className="inline-feedback" role="status">{message}</div>}{busy ? <div className="panel empty-state">Loading sessions…</div> : sessions.length === 0 ? <div className="panel empty-state">No sessions yet. Start one when the table is ready.</div> : <>{active.length > 0 && <><div className="section-label session-group-label">CURRENT SESSION</div><div className="session-list">{active.map(row)}</div></>}{history.length > 0 && <><div className="section-label session-group-label">SESSION HISTORY</div><div className="session-list">{history.map(row)}</div></>}</>}{editing && <Modal title="Edit session" eyebrow="AUTOSAVED SESSION DETAILS" onClose={() => setEditing(null)}><label className="form-label">Title<input className="form-input" value={draft.title} onChange={event => setDraft(current => ({ ...current, title: event.target.value }))} /></label><label className="form-label">Notes<textarea className="form-input config-textarea" value={draft.notes} onChange={event => setDraft(current => ({ ...current, notes: event.target.value }))} /></label><div className="save-indicator" role="status" aria-live="polite">{saveState}</div></Modal>}{ending && <Modal title={`End ${ending.title}?`} eyebrow="END ACTIVE SESSION" onClose={() => setEnding(null)}><p>This closes the active session and keeps its events in history. You can start another session later.</p><div className="modal-actions"><button className="button secondary" onClick={() => setEnding(null)}>Keep active</button><button className="button primary" onClick={end}>End session</button></div></Modal>}</>;
}
