import React, { useState } from 'react';
import CharacterEditor from './CharacterEditor';
import beastforms from './content/daggerforge/srd/beastforms.json';

type Props = { c: any; disabled: boolean; onUpdate: (id: string, change: Record<string, any>, text: string) => void | Promise<void>; onAdvance?: () => void };
const druidElements = ['air', 'earth', 'fire', 'water'];
const sorcererElements = ['air', 'earth', 'fire', 'lightning', 'water'];

function DiceTrack({ label, values, max, disabled, onChange }: { label: string; values: number[]; max: number; disabled: boolean; onChange: (values: number[]) => void }) {
  const update = (index: number, value: number) => onChange(values.map((die, i) => i === index ? Math.max(1, Math.min(max, value || 1)) : die));
  return <div className="specialized-track"><div className="card-title"><h4>{label}</h4><button className="text-button" disabled={disabled || values.length >= 6} onClick={() => onChange([...values, max])}>Add die</button></div><div className="dice-list">{values.length ? values.map((value, index) => <label className="form-label" key={`${label}-${index}`}>Die {index + 1}<input className="form-input compact-number" type="number" min="1" max={max} disabled={disabled} value={value} onChange={event => update(index, Number(event.target.value))} /></label>) : <span className="muted-copy">No dice tracked.</span>}</div>{values.length > 0 && <button className="text-button danger-text" disabled={disabled} onClick={() => onChange(values.slice(0, -1))}>Remove last die</button>}</div>;
}

export default function SpecializedCharacterEditor({ c, disabled, onUpdate, onAdvance }: Props) {
  const [companionExperience, setCompanionExperience] = useState('');
  const special = c.className === 'Druid' ? 'druid' : c.className === 'Ranger' && c.subclassName === 'Beastbound' ? 'companion' : c.className === 'Sorcerer' && c.subclassName === 'Elemental Origin' ? 'element' : c.className === 'Seraph' && c.subclassName === 'Divine Wielder' ? 'prayer' : c.className === 'Warrior' && c.subclassName === 'Call of the Slayer' ? 'slayer' : '';
  const save = (change: Record<string, any>, text: string) => onUpdate(c.id, change, text);
  return <>
    <CharacterEditor c={c} disabled={disabled} onUpdate={onUpdate} onAdvance={onAdvance} />
    {special === 'druid' && <section className="sheet-card specialized-sheet"><div className="card-title"><div><span className="section-label">DRUID · BEASTFORM</span><h3>{c.beastformName || 'Beastform not configured'}</h3></div><span>{disabled ? 'Locked in PLAY' : 'Configuration + runtime'}</span></div><div className="config-grid"><label className="form-label">Beastform<select className="form-input" disabled={disabled} value={c.beastformName || ''} onChange={event => save({ beastformName: event.target.value }, `selected ${event.target.value} Beastform`)}><option value="">Choose Beastform</option>{(beastforms as any[]).filter(form => Number(form.tier) <= Number(c.level || 1)).map(form => <option key={form.name} value={form.name}>{form.name} · Tier {form.tier} · {form.examples}</option>)}</select></label>{c.subclassName === 'Warden of the Elements' && <label className="form-label">Channel element<select className="form-input" disabled={disabled} value={c.channelElement || ''} onChange={event => save({ channelElement: event.target.value }, `set channel element to ${event.target.value}`)}><option value="">Choose element</option>{druidElements.map(item => <option key={item} value={item}>{item}</option>)}</select></label>}</div><label className="form-label">Beastform Stress<input className="form-input compact-number" type="number" min="0" max="6" disabled={false} value={c.beastformStress || 0} onChange={event => save({ beastformStress: Math.max(0, Math.min(6, Number(event.target.value))) }, 'updated Beastform Stress')} /></label><small className="muted-copy">The selected form is configuration; Stress is runtime state and remains editable in PLAY.</small></section>}
    {special === 'companion' && <section className="sheet-card specialized-sheet"><div className="card-title"><div><span className="section-label">RANGER · BEASTBOUND COMPANION</span><h3>{c.companion?.name || 'Companion not configured'}</h3></div><span>Evasion 10 · Stress {c.companion?.stress || 0}/{c.companion?.stressMax || 6}</span></div><label className="form-label">Companion name<input className="form-input" disabled={disabled} value={c.companion?.name || ''} onChange={event => save({ companion: { ...(c.companion || {}), name: event.target.value, evasion: 10, stressMax: 6 } }, 'updated companion name')} /></label><div className="config-grid"><label className="form-label">Companion Stress<input className="form-input" type="number" min="0" max="6" disabled={false} value={c.companion?.stress || 0} onChange={event => save({ companion: { ...(c.companion || {}), stress: Math.max(0, Math.min(6, Number(event.target.value))), evasion: 10, stressMax: 6 } }, 'updated companion Stress')} /></label><label className="form-label">Add Experience<input className="form-input" disabled={disabled || (c.companion?.experiences || []).length >= 2} value={companionExperience} onChange={event => setCompanionExperience(event.target.value)} onBlur={() => { if (companionExperience.trim()) { save({ companion: { ...(c.companion || {}), experiences: [...(c.companion?.experiences || []), { text: companionExperience.trim(), modifier: '+2' }].slice(0, 2), evasion: 10, stressMax: 6 } }, 'updated companion Experiences'); setCompanionExperience(''); } }} placeholder="Up to two experiences" /></label></div><div className="muted-copy">Attack: d6 physical · Melee range. The companion marks Stress instead of Hit Points.</div>{(c.companion?.experiences || []).map((item: any) => <div className="experience-row" key={item.text}><span>{item.text}</span><b>{item.modifier || '+2'}</b></div>)}</section>}
    {special === 'element' && <section className="sheet-card specialized-sheet"><div className="card-title"><span className="section-label">SORCERER · ELEMENTAL ORIGIN</span><span>Configuration</span></div><label className="form-label">Element<select className="form-input" disabled={disabled} value={c.element || ''} onChange={event => save({ element: event.target.value }, `selected ${event.target.value} as elemental origin`)}><option value="">Choose element</option>{sorcererElements.map(item => <option key={item} value={item}>{item}</option>)}</select></label></section>}
    {special === 'prayer' && <section className="sheet-card specialized-sheet"><div className="card-title"><div><span className="section-label">SERAPH · DIVINE WIELDER</span><h3>Prayer Dice</h3></div><span>Runtime resource</span></div><DiceTrack label="Prayer Dice · d4" values={Array.isArray(c.prayerDice) ? c.prayerDice : []} max={4} disabled={false} onChange={values => save({ prayerDice: values }, 'updated Prayer Dice')} /><small className="muted-copy">Prayer Dice are tracked on the sheet during play and do not alter the character’s configuration.</small></section>}
    {special === 'slayer' && <section className="sheet-card specialized-sheet"><div className="card-title"><div><span className="section-label">WARRIOR · CALL OF THE SLAYER</span><h3>Slayer Dice</h3></div><span>Runtime resource</span></div><DiceTrack label="Slayer Dice · d6" values={Array.isArray(c.slayerDice) ? c.slayerDice : []} max={6} disabled={false} onChange={values => save({ slayerDice: values }, 'updated Slayer Dice')} /><small className="muted-copy">Slayer Dice are tracked on the sheet during play and can be adjusted as the feature changes them.</small></section>}
  </>;
}
