import React, { useEffect, useState } from 'react';
import { apiRequest, getApiSession } from './api';
import { Modal } from './ProductionOverlays';
type Adversary = { id: string; name: string; hp: number; hpMax: number; defeated: boolean };
type Encounter = { id: string; name: string; status: string; adversaries: Adversary[] };
export default function TableRuntimeControls() {
  const session = getApiSession(); const [encounters, setEncounters] = useState<Encounter[]>([]); const [selected, setSelected] = useState(''); const [editing, setEditing] = useState<Adversary | null>(null); const [name, setName] = useState(''); const [amount, setAmount] = useState(1); const [message, setMessage] = useState('');
  const load = async () => { if (!session) return; try { const data = await apiRequest<{ encounters: Encounter[] }>(`/api/campaigns/${session.campaignId}`); setEncounters(data.encounters || []); setSelected(current => current || data.encounters?.find(item => item.status === 'ACTIVE')?.id || ''); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load runtime controls.'); } };
  useEffect(() => { void load(); const sync = (event: Event) => { if ((event as CustomEvent).detail?.entityType === 'encounter') void load(); }; window.addEventListener('df-realtime-event', sync); return () => window.removeEventListener('df-realtime-event', sync); }, []);
  const encounter = encounters.find(item => item.id === selected) || encounters.find(item => item.status === 'ACTIVE'); const patch = async (body: Record<string, unknown>) => { if (!session || !encounter) return; try { const updated = await apiRequest<Encounter>(`/api/campaigns/${session.campaignId}/encounters/${encounter.id}`, { method: 'PATCH', body: JSON.stringify(body) }); setEncounters(current => current.map(item => item.id === updated.id ? updated : item)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to update runtime state.'); } };
  if (!encounter) return null; return <section className="panel runtime-controls"><div className="panel-head"><div><span className="section-label">RUNTIME INSTANCE</span><h2>Adversary controls</h2></div><select className="form-input" value={encounter.id} onChange={event => setSelected(event.target.value)} aria-label="Select runtime encounter">{encounters.map(item => <option key={item.id} value={item.id}>{item.name} · {item.status}</option>)}</select></div><p className="muted-copy">Use explicit damage/healing amounts and manage each runtime instance without changing the reusable library definition.</p>{encounter.adversaries.map(adversary => <div className="runtime-adversary" key={adversary.id}><div><b>{adversary.name}</b><span>{adversary.hp} / {adversary.hpMax} HP · {adversary.defeated ? 'Defeated' : 'Active'}</span></div><button className="text-button" onClick={() => { setEditing(adversary); setName(adversary.name); }}>Edit</button><button className="text-button" onClick={() => patch({ adversaryId: adversary.id, hp: Math.max(0, adversary.hp - Math.max(1, amount)) })}>Damage</button><button className="text-button" onClick={() => patch({ adversaryId: adversary.id, hp: Math.min(adversary.hpMax, adversary.hp + Math.max(1, amount)) })}>Heal</button></div>)}<label className="form-label runtime-amount">Amount<input className="form-input" type="number" min="1" value={amount} onChange={event => setAmount(Math.max(1, Number(event.target.value)))} /></label>{message && <div className="form-error" role="alert">{message}</div>}{editing && <Modal title={`Manage ${editing.name}`} eyebrow="RUNTIME INSTANCE" onClose={() => setEditing(null)}><label className="form-label">Display name<input className="form-input" value={name} onChange={event => setName(event.target.value)} /></label><div className="modal-actions"><button className="button secondary" onClick={() => setEditing(null)}>Cancel</button><button className="button secondary" onClick={async () => { await patch({ removeAdversaryId: editing.id }); setEditing(null); }}>Remove instance</button><button className="button primary" onClick={async () => { if (name.trim()) await patch({ renameAdversary: { adversaryId: editing.id, name: name.trim() } }); setEditing(null); }}>Save name</button></div></Modal>}</section>;
}
